BAN_MESSAGES = [
    "💀 **You dare return, mortal?**\nThis bot has banished you to the Shadow Realm.\nGo cry to your waifu, because you’re not welcome here.",
    "😒 **Notice me? Nope.**\nYou’ve been banned for being a pain.\nGo binge some filler episodes and think about what you’ve done.",
    "👑 **Access Denied, Peasant!**\nThis anime kingdom has no room for rule-breakers.\nTry another bot-if they’ll even take you.",
    "🚷 **You’ve been exiled from the anime club!**\nMaybe next time, don’t act like a villain. No downloads for you!",
    "🛑 **Banned.**\nYou broke the rules, now face the consequences. Go touch grass.",
    "📺 **To Be Continued...**\n...in another bot. You’re banned here. GG.",
    "🦹‍♂️ **The dark seal of BAN has been placed upon you!**\nOnly the worthy may lift it. (Spoiler: That’s not you.)",
    "🥷 **Ninja Vanish!**\nYou’ve been stealth-banned. Even Kakashi can’t help you now.",
    "🍜 **No ramen for you!**\nThis bot’s Ichiraku is closed to troublemakers. Try again in your next life.",
    "🧙‍♂️ **Your magic power is sealed!**\nThis isn’t a shounen-you don’t get a redemption arc here.",
    "🦊 **Kurama says NO!**\nYou’ve been banned harder than filler episodes in Naruto.",
    "🏯 **The anime gates are closed.**\nOnly true heroes may enter. Villains like you get the boot.",
    "🎭 **You’ve been unmasked!**\nThe real villain was you all along. Enjoy your ban, antagonist.",
    "🏮 **Festival’s over!**\nYou’ve been banned from the party. Go home and rethink your life choices.",
    "🦸‍♂️ **Not all heroes get a second chance.**\nYou’ve been banned. No plot armor for you!",
    "💢 **You’ve triggered the ban hammer!**\nThis is your anime filler episode-except you don’t come back.",
    "🛡️ **Shield Hero rejects you!**\nYou’ve been banned. There’s no isekai for you here."
]

searchmap = {
    "Demon Slayer": "Kimetsu no Yaiba",
    "Attack on Titan": "Shingeki no Kyojin",
    "The Beginning after the end": "Saikyou no Ousama",
    "Beginning after the end": "Saikyou no Ousama",
    "Classroom of the elite": "Youkoso Jitsuryoku"
}

mapping = {
    "A-Rank_Party_wo_Ridatsu_shita_Ore_wa,_Moto_Oshiego-tachi_to_Meikyuu_Shinbu_wo_Mezasu_(TV)": "A-Rank",
    "Active_Raid:_Kidou_Kyoushuushitsu_Dai_Hachi_Gakari_2nd_(TV)": "Active_Raid_S2",
    "Akuyaku_Reijou_Level_99:_Watashi_wa_Ura-Boss_desu_ga_Maou_dewa_Arimasen_(TV)": "Akuyaku_Reijou_Level_99",
    "Alice_in_the_Country_of_Hearts:_Wonderful_Wonder_World_(Movie)": "Alice_in_the_Country",
    "Ancien_to_Mahou_no_Tablet:_Mou_Hitotsu_no_Hirune_Hime_(ONA)": "Ancien_to_Mahou",
    "Ane_Log:_Moyako_Neesan_no_Honpen_wo_Tobidashite_Tomaranai_Monologue_(TV)": "Ane_Log",
    "Araiso_Private_High_School_Student_Council_Executive_Committee_(OVA)": "Araiso_Private",
    "Ateuma_Chara_no_Kuse_Shite,_Spadali_Oji_ni_Chouai_Sarete_Imasu_(TV)": "Ateuma_Chara",

    "Bishoujo_Senshi_Sailor_Moon_Crystal:_Death_Busters-hen_(TV)": "Bishoujo_Senshi_Death",
    "Boruto:_Naruto_the_Movie_-_Naruto_ga_Hokage_ni_Natta_Hi_(Special)": "Boruto_Movie_Hokage",
    "Botsuraku_Yotei_no_Kizoku_dakedo,_Hima_datta_kara_Mahou_wo_Kiwametemita_(TV)": "Botsuraku",
    "Boukensha_ni_Naritai_to_Miyako_ni_Deteitta_Musume_ga_S-Rank_ni_Natteta_(TV)": "Boukensha_ni_Naritai",
    "Buddy_Complex:_Kanketsu-hen_-_Ano_Sora_ni_Kaeru_Mirai_de_(Special)": "Buddy_Complex_Special",
    "Buta_no_Gotoki_Sanzoku_ni_Torawarete_Shojo_wo_Ubawareru_Kyonyuu_Himekishi___Onna_Senshi_(TV)": "Buta_no_Gotaku",

    "Cheat_Kusushi_no_Slow_Life:_Isekai_ni_Tsukurou_Drugstore_(TV)": "Cheat_Drugstore",
    "Chiba_Pedal:_Yowamushi_Pedal_to_Manabu_Jitensha_Koutsuu_Anzen_(ONA)": "Chiba_pedal_Anzen",
    "Chiisana_Ahiru_no_Ooki_na_Ai_no_Monogatari:_Ahiru_no_Kwak_(TV)": "Chiisana_Ahiru",
    "Chiisana_Koi_no_Monogatari:_Chichi_to_Sally_Hatsukoi_no_Shiki_(Special)": "Chiisana_Monogatari",
    "Choujin_Koukousei_tachi_wa_Isekai_demo_Yoyuu_de_Ikinuku_you_desu!_(TV)": "Choujin_Koukousei",
    "City_Hunter:_Kinkyuu_Namachuukei!__Kyouakuhan_Saeba_Ryou_no_Saigo_(Special)": "City_hunter_Saeba",
    "Corpse_Party:_Tortured_Souls_-_Bougyakusareta_Tamashii_no_Jukyou_(OVA)": "Corpse_Party_Souls",

    "Danganronpa_3:_The_End_of_Kibougamine_Gakuen_-_Kibou-hen_(Special)": "Danganronpa_3_Kibou_hen",
    "Danganronpa_3:_The_End_of_Kibougamine_Gakuen_-_Zetsubou-hen_(TV)": "Danganronpa_Zetsubou_hen",
    "Danganronpa_3:_The_End_of_Kibougamine_Gakuen_____Mirai-hen_(TV)": "Danganronpa_Mirai_hen",
    "Danganronpa:_Kibou_no_Gakuen_to_Zetsubou_no_Koukousei_-_The_Animation_(TV)": "Danganronpa_The_Animation",
    "Darker_than_BLACK:_Kuro_no_Keiyakusha_Gaiden_(TV)": "Darker_than_BLACK_kuro",
    "Death_March_kara_Hajimaru_Isekai_Kyousoukyoku_(TV)": "Death_March_kara_Hajimaru",
    "Dekisokonai_to_Yobareta_Motoeiyuu_wa_Jikka_kara_Tsuihou_sareta_node_Sukikatte_ni_Ikiru_Koto_ni_Shita_(TV)": "Dekisokonai_Yobareta",
    "Dengeki_Oshioki_Musume_Gootaman_R:_Ai_to_Kanashimi_no_Final_Battle_(OVA)": "Dengeki_Oshioki_Battle",
    "Dengeki_Oshioki_Musume_Gootaman:_Gootaman_Tanjou-hen_(OVA)": "Dengeki_Gootaman",
    "Detective_Conan_Movie_06:_The_Phantom_of_Baker_Street_(Movie)": "Detective_Conan_Mov_06",
    "Detective_Conan:_Magician_of_the_Silver_Sky_(movie_8)_(Movie)": "Detective_Conan_Mov_08",
    "Detective_Conan:_Strategy_Above_the_Depths_(movie_9)_(Movie)": "Detective_Conan_Mov_09",
    "Detective_Conan:_The_Crimson_Love_Letter_(movie_21)_(Movie)": "Detective_Conan_Mov_21",
    "Detective_Conan:_The_Darkest_Nightmare_(movie_20)_(Movie)": "Detective_Conan_Mov_20",
    "Detective_Conan:_The_Private_Eyes_Requiem_(movie_10)_(Movie)": "Detective_Conan_Mov_10",
    "Digimon_Xros_Wars:_Toki_o_Kakeru_Sh__nen_Hunter-tachi_(TV)": "Digimon_Xros_Shonen",
    "Dorami___Doraemons:_Robot_Schools_Seven_Mysteries_(Movie)": "Dorami_Doraemon_Robot",
    "Druaga_no_Tou:_The_Aegis_of_Uruk_-_Jil_no_Bouken_(Special)": "Druaga_Jil",
    "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_(TV)": "Danmachi",
    "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_Gaiden:_Sword_Oratoria_(TV)": "Danmachi_Sword",
    "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_II_(TV)": "Danmachi_2",
    "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_III_(TV)": "Danmachi_3",
    "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_IV:_Shin_Shou_-_Meikyuu-hen_(TV)": "Danmachi_4",
    "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_V:_Houjou_no_Megami-hen_(TV)": "Danmachi_5",
    "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_no_Darou_ka_IV:_Fuka_Shou_-_Yakusai-hen_(TV)": "Danmachi_Fuka",
    
    "Ebisugawa_Public_High_School_Astronomical_Club_(TV)": "Ebisugawa_Club",
    "Ebiten:_Kouritsu_Ebisugawa_Koukou_Tenmonbu_(ONA)": "Ebiten_Koukou",
    "Eiga_Kuma_no_Gakkou:_Patissier_Jackie_to_Ohisama_no_Sweets_(Movie)": "Eiga_Kuma_Sweets",
    "Eiga_Precure_All_Stars_DX3:_Mirai_ni_Todoke!_Sekai_wo_Tsunagu_Niji-iro_no_Hana_(Movie)": "Eiga_Precure",
    "Eiyuuou,_Bu_wo_Kiwameru_Tame_Tenseisu._Soshite,_Sekai_Saikyou_no_Minarai_Kishi_(TV)": "Eiyuuou_Tame_Sekai",
    "Embracing_Love:_Cherished_Spring_(Haru_wo_Daiteita)_(OVA)": "Embracing_Love_Spring",
    "Escha___Logy_no_Atelier:_Tasogare_no_Sora_no_Renkinjutsushi_(TV)": "Escha_no_Sora",
    "Eureka_Seven_AO:_Jungfrau_no_Hanabanatachi_(OVA)": "Eureka_Seven_ov",

    "Fairy_Ranmaru:_Anata_no_Kokoro_Otasuke_Shimasu_(TV)": "Fairy_Ranmaru_Anata",
    "Fate_Grand_Order:_Zettai_Majuu_Sensen_Babylonia_(TV)": "Fate_Grand_order_Babylonia",
    "Final_Fantasy_VII_:_On_the_Way_to_A_Smile_Episode_Denzel_(TV)": "Final_Fantasy_VII_Denzel",
    "Final_Fantasy_VII_-_Dirge_Of_Cerberus_CG_Movies_(Movie)": "Final_Fantasy_VII_Cerberus",
    "Fortune_Quest:_Yo_ni_mo_Shiawase_na_Boukensha-tachi_(OVA)": "Fortune_Quest_Boukensha",
    "Fuguushoku__Kanteishi__ga_Jitsuwa_Saikyou_Datta:_Naraku_de_Kitaeta_Saikyou_no__Shingan__de_Musousuru_(TV)": "Fuguushoku_Kanteishi_Saikyou",
    "Full_Moon_O_Sagashite:_Cute_Cute_Adventure_(Special)": "Full_Moon_Cute_Cute",
    "Futsuu_no_Joshikousei_ga__Locodol__Yatte_Mita_(TV)": "Futsuu_Joshikousei_Locodol",

    "Gaikotsu_Kishi-sama,_Tadaima_Isekai_e_Odekakechuu_(TV)": "Gaikotsu_Tadaima_Isekai",
    "Gekijouban_Gintama_Kanketsu-hen:_Yorozuya_yo_Eien_Nare_(Movie)": "Gekijouban_Gintama_Yorozuya",
    "Gekijouban_Toriko_Bishokushin_no_Special_Menu_(Movie)": "Gekijouban_Torika_Spe",
    "Genjitsu_Shugi_Yuusha_no_Oukoku_Saikenki_Part_2_(TV)": "Genjitsu_Shugi_Yuusha_Part_2",
    "Geobreeders_2:_Mouryou_Yuugekitai_File-XX_Ransen_Toppa_(OVA)": "Geobreeders_2_Toppa",
    "Ghost_in_the_Shell_Arise:_Alternative_Architecture_(TV)": "Ghost_in_the_Shell_Architecture",
    "Ghost_in_the_Shell:_S.A.C._Solid_State_Society_(Movie)": "Ghost_in_the_Shell_Solid",
    "Ginga_Eiyuu_Densetsu:_Die_Neue_These_-_Kaikou_(TV)": "Ginga_Eiyuu_Kaikou",
    "Ginga_Eiyuu_Densetsu:_Die_Neue_These_-_Sakubou_(TV)": "Ginga_Eiyuu_Sakubou",
    "Gorilla_no_Kami_kara_Kagosareta_Reijou_wa_Ouritsu_Kishi-dan_de_Kawaigarareru_(TV)": "Gorilla_no_Kami",
    "Guild_no_Uketsukejou_desu_ga,_Zangyou_wa_Iya_nano_de_Boss_wo_Solo_Toubatsu_Shiyou_to_Omoimasu_(TV)": "Guild_no_Uketsukejou",
    "Gyakuten_Saiban:_Sono_Shinjitsu,_Igi_Ari!_(TV)": "Gyakuten_Saiban",
    "Gyakuten_Saiban:_Sono_Shinjitsu,_Igi_Ari!_Season_2_(TV)": "Gyakuten_Saiban_2",

    "Hanayaka_Nari,_Waga_Ichizoku:_Kinetograph_(OVA)": "Hanayaka_Nari",
    "Hanyou_no_Yashahime:_Sengoku_Otogizoushi_-_Ni_no_Shou_(TV)": "Hanyou_no_Sengoku",
    "Harukanaru_Toki_no_Naka_de:_Ajisai_Yumegatari_(OVA)": "Harukanaru_Toki_ov",
    "Harukanaru_Toki_no_Naka_de_2:_Shiroki_Ryuu_no_Miko_(OVA)": "Harukanaru_Toki_2_ov",
    "Harukanaru_Toki_no_Naka_de_3:_Owarinaki_Unmei_(Special)": "Harukanaru_Toki_3_sp",
    "Harukanaru_Toki_no_Naka_de_3:_Kurenai_no_Tsuki_(Special)": "Harukanaru_Toki_3_kurenai",
    "Honzuki_no_Gekokujou:_Shisho_ni_Naru_Tame_ni_wa_Shudan_wo_Erandeiraremasen_3rd_Season_(TV)": "Honzuki_3",
    "Hayate_no_Gotoku_(2012)_-_Can___t_Take_My_Eyes_Off_You_(TV)":  "Hayate_2012",
    "Hayate_no_Gotoku_(2012):_Can___t_Take_My_Eyes_Off_You_(TV)": "Hayate_2012",
    "Hazure_Skill_Kinomi_Master:_Skill_no_Mi_(Tabetara_Shinu)_wo_Mugen_ni_Taberareru_You_ni_Natta_Ken_ni_Tsuite_(TV)": "Hazure_Skill",
    "Hazurewaku_no_Joutai_Ijou_Skill_de_Saikyou_ni_Natta_Ore_ga_Subete_wo_Juurin_suru_made_(TV)": "Hazurewaku_no_Joutai",
    "Hengen_Taima_Yakou_Karura_Mau!_Nara_Onryou_Emaki_(Movie)": "Hengen_Taima",
    "Hengen_Taima_Yakou_Karura_Mau!_Sendai_Kokeshi_Enka_(OVA)":"Hengen_Taima_Yakou",
    "Heroine_Tarumono!_Kiraware_Heroine_to_Naisho_no_Oshigoto_(TV)":"Heroine_Tarumono!_Kirawara",
    "Hifuu_Katsudou_Kiroku:_The_Sealed_Esoteric_History_(OVA)":"Hifuu_Katsudou",
    "Higeki_no_Genkyou_to_Naru_Saikyou_Gedou_Last_Boss_Joou_wa_Tami_no_Tame_ni_Tsukushimasu_(TV)":"Higeki_no_Genkyou",
    "Highschool_of_the_Dead:_Drifters_of_the_Dead_(OVA)":"Highschool_dead",
    "Hitomi_no_Naka_no_Shounen:_Juugo_Shounen_Hyouryuuki_(Special)":"Hitomi_Shounen",
    "Honzuki_no_Gekokujou:_Shisho_ni_Naru_Tame_ni_wa_Shudan_wo_Erandeiraremasen_(TV)":"Honzuki_Shudan",
    "Honzuki_no_Gekokujou:_Shisho_ni_Naru_Tame_ni_wa_Shudan_wo_Erandeiraremasen_2nd_Season_(TV)":"Honzuki_Shudan_2nd",
    "Hoshi_ni_Negai_wo:_Cold_Body___Warm_Heart_(ONA)":"Hoshi_ni_Negai",
    "Hypnosis_Mic:_Division_Rap_Battle_-_Rhyme_Anima___(TV)":"Hypnosis_Mic",
    
    "Hayate_no_Gotoku!_Heaven_Is_a_Place_on_Earth_(Movie)":"Hayate_gotoku!",
    "Hataraku_Otona_no_Renai_Jijou_The_Animation_(OVA)":"Hataraku_Otona",

    
    "I_Was_Reincarnated_as_the_7th_Prince_So_I_Can_Take_My_Time_Perfecting_My_Magical_Ability_(TV)": "Reincarnated_7th_Prince",
    "Ikemen Sengoku: Toki wo Kakeru ga Koi wa Hajimaranai (TV)": "Ikeman_sengoku",
    "Inferious_Wakusei_Senshi_Gaiden_Condition_Green_(OVA)": "Inferious_Wakusei",
    "Interstella_555:_the_story_of_the_secret_star_system_(Movie)": "Interstella_555",
    "InuYasha_Movie_2_-_Castle_Beyond_the_Looking_Glass_(Movie)": "InuYasha_Looking_Glass",
    "InuYasha_the_Movie_1_-_Affections_Touching_Across_Time_(Movie)": "InuYasha_Across_Time",
    "InuYasha_the_Movie_3:_Swords_of_an_Honorable_Ruler_(Movie)": "InuYasha_Hoorable_Ruler",
    "Isekai_de_Cheat_Skill_wo_Te_ni_Shita_Ore_wa,_Genjitsu_Sekai_wo_mo_Musou_Suru:_Level_Up_wa_Jinsei_wo_Kaeta_(TV)": "Isekai_de_Cheat_Skill",
    "Isekai_de_Mofumofu_Nadenade_suru_Tame_ni_Ganbattemasu_(TV)": "Isekai_Mofumofu",
    "Isekai_Izakaya:_Koto_Aitheria_no_Izakaya_Nobu_(TV)": "Isekai_Izakaya_Nobu",
    "Isekai_Maou_to_Shoukan_Shoujo_no_Dorei_Majutsu_(TV)": "Isekai_Maou_Dorei",
    "Isekai_Maou_to_Shoukan_Shoujo_no_Dorei_Majutsu____(TV)": "Isekai_Maou_dorei_2",
    "Isekai_Yururi_Kikou:_Kosodateshinagara_Boukensha_Shimasu_(TV)": "Isekai_Yururi_Shimasu",
    "Issho_ni_Training_Ofuro_Bathtime_with_Hinako___Hiyoko_(OVA)": "Isho_ni_Training_Hinako",
    "Isshun_de_Chiryoushiteita_no_ni_Yakudatazu_to_Tsuihousareta_Tensai_Chiyushi,_Yami_Healer_Toshite_Tanoshiku_Ikiru_(TV)": "Isshun_Chiyushi",
    "Itai_no_wa_Iya_nano_de_Bougyoryoku_ni_Kyokufuri_Shitai_to_Omoimasu_(TV)": "Itai_Shitai_Omaimasu",
    "Itai_no_wa_Iya_nano_de_Bougyoryoku_ni_Kyokufuri_Shitai_to_Omoimasu._2_(TV)": "Itai_Shitai_Omaimasu_2",
    "Iya_na_Kao_sare_nagara_Opantsu_Misete_Moraitai_(ONA)": "Iya_na_Misete",
    "Iya_na_Kao_sare_nagara_Opantsu_Misete_Moraitai_2_(ONA)": "Iya_na_Misete_2",
    
    "Janguru_wa_Itsumo_Hale_nochii_Guu_Deluxe_(TV)": "Janguru",
    "Jidou_Hanbaiki_ni_Umarekawatta_Ore_wa_Meikyuu_wo_Samayou_(TV)": "Jidou_Hanbaiki",
    "Jimihen!!:_Jimiko_wo_Kaechau_Jun_Isei_Kouyuu!!_(TV)": "jimihen_Jun_Isei",
    "JoJos_Bizarre_Adventure_Part_6:_Stone_Ocean_(TV)": "Jojos_6_Ocean",
    "JoJo_no_Kimyou_na_Bouken:_Diamond_wa_Kudakenai_(TV)": "JoJo_Diamond_Kudakenai",
    "JoJos_Bizarre_Adventure:_Stardust_Crusaders_(TV)": "Jojos_Stardust_Crusaders",
    
    "Joshiochi!:_2-kai_kara_Onnanoko_ga..._Futtekita!__(TV)": "Joshiochi",
    "Jubei-chan_2:_The_Counterattack_of_Siberia_Yagyu_(TV)":"Jubei_chan_2",

    "Kage_no_Jitsuryokusha_ni_Naritakute!_2nd_Season_(TV)": "Kage_Jitsuryokusha_2",
    "Kaguya-sama_wa_Kokurasetai_-Ultra_Romantic-_(TV)": "Kaguya_Ultra_Romantic",
    "Kaguya-sama_wa_Kokurasetai:_Tensai-tachi_no_Renai_Zunousen_Season_2_(TV)": "Kaguya_Tensai_2",
    "Kaguya-sama_wa_Kokurasetai:_Ultra_Romantic_(TV)": "Kaguya_Ultra_Romantic_2",
    "Kaguya-sama_wa_Kokurasetai_:_Tensai-tachi_no_Renai_Zunousen_2nd_Season_(TV)": "Kaguya_Tensai_2nd",
    "Kaijuu_Girls_Kuro:_Ultra_Kaijuu_Gijinka_Keikaku_(Movie)": "Kaijuu_Girls_Kuro",
    "Kaijuu_Girls:_Ultra_Kaijuu_Gijinka_Keikaku_2nd_Season_(TV)": "Kaijuu_Girls_2",
    "Kaiko_Sareta_Ankoku_Heishi_(30-dai)_no_Slow_na_Second_Life_(TV)": "Kaiko_Ankoku_Heishi",
    "Kakyuusei_2:_Hitomi_no_Naka_no_Shoujo-tachi_(TV)": "Kakyuusei_2_Hitomi",
    "Kanojo_x_Kanojo_x_Kanojo:_Sanshimai_to_no_DokiDoki_Kyoudou_Seikatsu_(OVA)": "Kanojo_x3_Sanshimai",
    "Kanpekisugite_Kawaige_ga_Nai_to_Konyakuhakisareta_Seijo_wa_Ringoku_ni_Urareru_(TV)": "Kanpeki_Seijo_Ringoku",
    "Katainaka_no_Ossan,_Kensei_ni_Naru:_Tada_no_Inaka_no_Kenjutsu_Shihan_datta_no_ni,_Taiseishita_Deshi-tachi_ga_Ore_wo_Hottekurenai_Ken_(TV)": "Katainaka_Kensei",
    "Katsute_Mahou_Shoujo_to_Aku_wa_Tekitai_shiteita_(TV)": "Katsute_Mahou_Aku",
    "Kawaikereba_Hentai_demo_Suki_ni_Natte_Kuremasu_ka_(TV)": "Kawaikereba_Hentai",
    "Kaze_no_Naka_no_Shoujo:_Kinpatsu_no_Jeanie_(TV)": "Kaze_Shoujo_Jeanie",
    "Keikenzumi_na_Kimi_to,_Keiken_Zero_na_Ore_ga,_Otsukiai_suru_Hanashi_(TV)": "Keikenzumi_Keiken_Zero",
    "Keishicho_Tokumu-bu_Tokushu_Kyoaku-han_Taisaku-Shitsu_Dai-Nana-ka:_Tokunana_(TV)": "Keishicho_Tokunana",
    "Kimi_no_Koto_ga_Daidaidaidaidaisuki_na_100-nin_no_Kanojo_(TV)": "100_Kanojo",
    "Kimi_no_Koto_ga_Daidaidaidaidaisuki_na_100-nin_no_Kanojo_2nd_Season_(TV)": "100_Kanojo_2",
    "Kimi_to_Boku_no_Saigo_no_Senjou,_Aruiwa_Sekai_ga_Hajimaru_Seisen_(TV)": "Kimi_Boku_Seisen",
    "Kimi_to_Boku_no_Saigo_no_Senjou,_Aruiwa_Sekai_ga_Hajimaru_Seisen_Season_II_(TV)": "Kimi_Boku_Seisen_2",
    "Knights_of_the_Zodiac:_Saint_Seiya_-_Battle_for_Sanctuary_(TV)": "Saint_Seiya_Sanctuary",
    "Kindaichi_Shounen_no_Jikenbo:_Kuromajutsu_Satsujin_Jiken-hen_(OVA)": "Kindaichi_Kuromajutsu",
    "Kino_no_Tabi:_In_Order_to_Do_Something_-Life_Goes_On-_(Movie)": "Kino_Life_Goes_On",
    "Kino_no_Tabi:_The_Beautiful_World_-_The_Animated_Series_(TV)": "Kino_Beautiful_World",
    "Kinsou_no_Vermeil_~Gakeppuchi_Majutsushi_wa_Saikyou_no_Yakusai_to_Mahou_Sekai_wo_Tsukisusumu~_(TV)": "Kinsou_Vermeil",
    "Koi_suru_Tenshi_Angelique_~_Kokoro_no_Mezameru_Toki_(TV)": "Angelique_Kokoro",
    "Koi_Suru_Tenshi_Angelique_~Kagayaki_no_Ashita~_(TV)": "Angelique_Kagayaki",
    "Koi_to_Senkyo_to_Chocolate_(Koichoco,_Love,_Election___Chocolate)_(TV)": "Koichoco",
    "Kono_Naka_ni_Hitori,_Imouto_ga_Iru!_(NakaImo)_(TV)": "NakaImo",
    "Kono_Yuusha_ga_Ore_TUEEE_Kuse_ni_Shinchou_Sugiru_(TV)": "Yuusha_TUEEE",
    "Konyaku_Haki_sareta_Reijou_wo_Hirotta_Ore_ga,_Ikenai_Koto_wo_Oshiekom_(TV)": "Konyaku_Haki_Reijou",
    "Koori_Zokusei_Danshi_to_Cool_na_Douryou_Joshi_(TV)": "Koori_Zokusei_Cool",
    "Kosuke-sama_Rikimaru-sama:_Konpeitou_no_Ryuu_(OVA)": "Kosuke_Rikimaru_Ryuu",
    "Kubikiri_Cycle:_Aoiro_Savant_to_Zaregototsukai_(OVA)": "Kubikiri_Aoiro",
    "Kuroiwa_Medaka_ni_Watashi_no_Kawaii_ga_Tsuujinai_(TV)": "Kuroiwa_Medaka",
    "Kyou_Kara_Maou!_1st___2nd_Season_(TV)_(TV)": "Kyou_Kara_Maou_1_2",
    "Kyuukyoku_Shinka_shita_Full_Dive_RPG_ga_Genjitsu_yori_mo_Kusoge_Dattara_(TV)": "Kyuukyoku_Full_Dive",

    "La_Corda_DOro_~Secondo_Passo~_(TV)": "La_Corda_Secondo",
    "Last_Period:_Owarinaki_Rasen_no_Monogatari_(TV)": "Last_Period_Rasen",
    "Layton_Mystery_Tanteisha:_Katri_no_Nazotoki_File_(TV)": "Layton_Katri_File",
    "Legend_of_the_Galactic_Heroes_-_The_New_Thesis_-_Encounter_(TV)": "LotGH_New_Thesis",
    "Legends_of_the_Dark_King_-_A_Fist_of_the_North_Star_Story_(TV)": "Fist_North_Star_Dark",
    "Lime-iro_Senkitan:_The_South_Island_Dream_Romantic_Adventure_(OVA)": "Lime_iro_Senkitan",
    "Loop_7-kaime_no_Akuyaku_Reijou_wa,_Moto_Tekikoku_de_Jiyuu_Kimama_na_Hanayome_Seikatsu_wo_Mankitsu_suru_(TV)": "Loop_7_Akuyaku_Reijou",
    "Lord_El-Melloi_II_Sei_no_Jikenbo:_Rail_Zeppelin_Grace_Note_(TV)": "El_Melloi_Rail_Zeppelin",
    "Love_Live!_Nijigasaki_Gakuen_School_Idol_Doukoukai_(TV)": "Love_Live_Nijigasaki",
    "Love_Live!_Nijigasaki_Gakuen_School_Idol_Doukoukai_2nd_Season_(TV)": "Love_Live_Nijigasaki_2",
    "Lv2_kara_Cheat_datta_Motoyuusha_Kouho_no_Mattari_Isekai_Life_(TV)": "Lv2_Cheat_Motoyuusha",
    
    "Mahouka_Koukou_no_Rettousei:_Reminiscence_Arc_(Special)": "Mahouka_Reminiscence",
    "Mahoutsukai_ni_Narenakatta_Onnanoko_no_Hanashi_(TV)": "Mahoutsukai_Narenakatta",
    "Maji_de_Otaku_na_English!_Ribbon-chan:_Eigo_de_Tatakau_Mahou_Shoujo_(TV)": "Maji_Otaku_Ribbon",
    "Maji_de_Otaku_na_English!_Ribbon-chan:_Eigo_de_Tatakau_Mahou_Shoujo_-_The_TV_(TV)": "Maji_Otaku_Ribbon_TV",
    "Majokko_Club_Yoningumi:_A_Kuukan_kara_no_Alien_X_(OVA)": "Majokko_Alien_X",
    "Maou_Gakuin_no_Futekigousha:_Shijou_Saikyou_no_Maou_no_Shiso,_Tensei_shite_Shison-tachi_no_Gakkou_e_(TV)": "Maou_Gakuin_Futekigousha",
    "Maou_no_Ore_ga_Dorei_Elf_wo_Yome_ni_Shitanda_ga,_Dou_Medereba_Ii_(TV)": "Maou_Dorei_Elf",
    "Maougun_Saikyou_no_Majutsushi_wa_Ningen_datta_(TV)": "Maougun_Majutsushi",
    "Maeterlinck_no_Aoi_Tori:_Tyltyl_Mytyl_no_Bouken_Ryokou_(TV)": "Maeterlinck_Aoi_Tori",
    "Magia_Record:_Mahou_Shoujo_Madoka___Magica_Gaiden_(TV)": "Magia_Record_Madoka",
    "Magia_Record:_Mahou_Shoujo_Madoka___Magica_Gaiden_(TV)_2nd_Season_(TV)": "Magia_Record_Madoka_2",
    "Magia_Record:_Mahou_Shoujo_Madoka___Magica_Gaiden_Final_Season_-_Asaki_Yume_no_Akatsuki_(TV)": "Magia_Record_Final",
    "Mahou_Sensei_Negima!_~Mou_Hitotsu_no_Sekai~__(OVA)": "Negima_Hitotsu_Sekai",
    "Mahou_Sensei_Negima!_~Shiroki_Tsubasa_Ala_Alba~_(OVA)": "Negima_Ala_Alba",
    "Mahou_Shoujo_Nante_Mou_Ii_Desukara._2nd_Season_(TV)": "Mahou_Shoujo_Nante_2",
    "Mahou_Tsukai_ni_Taisetsu_na_Koto:_Natsu_no_Sora__(TV)": "Mahou_Tsukai_Natsu",
    "Mashin_Eiyuuden_Wataru:_Owarinaki_Toki_no_Monogatari_(OVA)": "Mashin_Eiyuuden_Wataru",
    "MASHLE_Kami_Shinkakusha_Kouho_Senbatsu_Shiken-hen_(TV)": "MASHLE_Kami_Shinkakusha",
    "Meitou_Isekai_no_Yu_Kaitakuki:_Around_40_Onsen_Mania_no_Tensei_Saki_wa,_Nonbiri_Onsen_Tengoku_deshita_(TV)": "Meitou_Isekai_Onsen",
    "Mobile_Suit_Gundam_40th_Anniversary_G40_Project_Special_Movie_(ONA)": "Gundam_G40",
    "Mobile_Suit_Gundam:_The_Origin_-_Zenya_Akai_Suisei_(TV)": "Gundam_Origin_Suisei",
    "Mobile_Suit_Gundam:_Suisei_no_Majo_Season_2_(TV)": "Gundam_Suisei_2",
    "Mobile_Suit_Gundam:_The_Origin_-_Zenya_Akai_Suisei_(TV)": "Gundam_Origin_Suisei_2",
    "Mondaiji-tachi_ga_Isekai_kara_Kuru_Sou_Desu_yo_(TV)": "Mondaiji_Isekai",
    "Monster_Strike_The_Movie:_Hajimari_no_Basho_e_(Movie)": "Monster_Strike_Movie",
    "Monster_Strike:_Zoku_Saishuu-banashi_-_Pandora_no_Hako_(ONA)": "Monster_Strike_Pandora",
    "Mori_no_Youki_na_Kobito-tachi:_Belfy_to_Lillibit_(TV)": "Mori_Youki_Kobito",
    "Muhyo_to_Rouji_no_Mahouritsu_Soudan_Jimusho_(TV)": "Muhyo_Rouji_Jimusho",
    "Muhyo_to_Rouji_no_Mahouritsu_Soudan_Jimusho_2nd_Season_(TV)": "Muhyo_Rouji_Jimusho_2",
    "Munto:Tenjou-jin_to_Akuto-jin_Saigo_no_Tatakai_(Movie)": "Munto_Tatakai",
    "Mushoku_Tensei_II:_Isekai_Ittara_Honki_Dasu_(TV)": "Mushoku_Tensei_2",
    "Mushoku_Tensei_II:_Isekai_Ittara_Honki_Dasu_Part_2_(TV)": "Mushoku_Tensei_2_2",
    "Mobile_Suit_Gundam_MS_IGLOO:_Apocalypse_0079_(OVA)": "Gundam_IGLOO_Apocalypse",
    "Mobile_Suit_Gundam_MS_IGLOO:_The_Hidden_One_Year_War_(OVA)": "Gundam_IGLOO_Hidden",
    "Mobile_Suit_Gundam_Seed_C.E.73:_Stargazer_(ONA)": "Gundam_Seed_Stargazer",
    "Mobile_Suit_Gundam:_Iron-Blooded_Orphans_2nd_Season_(TV)": "Gundam_IBO_2",
    "Mobile_Suit_Gundam_MS_IGLOO_2:_Juryoku_Sensen__(OVA)": "Gundam_IGLOO_Juryoku",
    "Merc_Storia:_Mukiryoku_no_Shounen_to_Bin_no_Naka_no_Shoujo_(TV)": "Merc_Storia_Mukiryoku",
    "Mushoku_Tensei:_Isekai_Ittara_Honki_Dasu_2nd_Season_(TV)": "Mushoku_Tensei_2nd",
    "My_mental_choices_are_completely_interfering_with_my_school_romantic_comedy_(TV)": "Mental_Choices_Comedy",
    
    "Naikaku_Kenryoku_Hanzai_Kyousei_Torishimarikan_Zaizen_Joutarou_(TV)": "Naikaku_Kenryoku_Zaizen",
    "Nanatsu_no_Taizai:_Mokushiroku_no_Yonkishi_(TV)": "Nanatsu_Yonkishi",
    "Nanatsu_no_Taizai:_Imashime_no_Fukkatsu_(TV)": "Nanatsu_Fukkatsu",
    "Nanatsu_no_Taizai:_Mokushiroku_no_Yonkishi_2nd_Season_(TV)": "Nanatsu_Yonkishi_2",
    "Nanatsu_no_Taizai:_Signs_of_Holy_War_(TV)": "Nanatsu_Holy_War",
    "Narutaru:_Mukuro_Naru_Hoshi_Tama_Taru_Ko_(TV)": "Narutaru_Mukuro",
    "Naruto_SD:_Rock_Lee_no_Seishun_Full-Power_Ninden_(TV)": "Rock_Lee_Ninden",
    "Naruto_SD:_Rock_Lee_no_Seishun_Full-Power_Ninden_Mou_Iccho_(TV)": "Rock_Lee_Ninden_2",
    "Naruto_Shippuden_Omake--Shippu!_Konoha_Gakuen_Den!_(Special)": "Naruto_Konoha_Gakuen",
    "Naruto_Shippuden_OVA_Sage_Naruto_vs_Sasuke_(OVA)": "Naruto_Sage_vs_Sasuke",
    "Naruto_Shippuden_Movie_6_-_Road_to_Ninja_(Movie)": "Naruto_Road_to_Ninja",
    "Naruto_Shippuden_Storm_Generations_OVA_(Special)": "Naruto_Storm_Generations",
    "Naruto_Shippuden:_Sunny_Side_Battle_(Special)": "Naruto_Sunny_Side",
    "Naruto_Shippuuden_Movie_4_-_The_Lost_Towers_(Movie)": "Naruto_Lost_Towers",
    "Naruto_Shippuuden_Movie_4:_Za_Rosuto_Taw___(Movie)": "Naruto_Rosuto_Taw",
    "Naruto_Shippuuden:_Hi_no_Ishi_o_Tsugumono_(Movie)": "Naruto_Hi_no_Ishi",
    "Naruto_the_Movie_Legend_of_the_Stone_of_Gelel_(Movie)": "Naruto_Gelel",
    "Naruto_the_Movie_Ninja_Clash_in_the_Land_of_Snow_(Movie)": "Naruto_Snow",
    "Naruto_the_Movie:_Guardians_of_the_Crescent_Moon_Kingdom_(Movie)": "Naruto_Crescent_Moon",
    "Naruto:_Takigakure_no_Shitou_-_Ore_ga_Eiyuu_Dattebayo!_(Special)": "Naruto_Takigakure",
    "Naruto:_Finally_a_Clash!!_Jounin_vs._Genin!_(OVA)": "Naruto_Jounin_vs_Genin",
    "Nasu:_A_Migratory_Bird_with_Suitcase_(OVA)": "Nasu_Migratory_Bird",
    "Nausica___of_the_Valley_of_the_Wind_(Movie)": "Nausica_Valley",
    "Naze_Boku_no_Sekai_wo_Daremo_Oboeteinai_no_ka_(TV)": "Naze_Boku_Sekai",
    "NEET_Kunoichi_to_Naze_ka_Dousei_Hajimemashita_(TV)": "NEET_Kunoichi",
    "Nejimaki_Seirei_Senki:_Tenkyou_no_Alderamin_(TV)": "Nejimaki_Alderamin",
    "Nekojiru_Gekijou_Jirujiru_Original_(TV)": "Nekojiru_Jirujiru",
    "Neo_Angelique_Abyss:_Second_Age_(TV)": "Neo_Angelique_Abyss",
    "Netoge_no_Yome_wa_Onnanoko_ja_Nai_to_Omotta_(TV)": "Netoge_Yome",
    "New_Dream_Hunter_Rem:_Yume_no_Kishitachi_(OVA)": "Dream_Hunter_Rem",
    "Night_Warriors_-_Darkstalkers_Revenge_(OVA)": "Night_Warriors_Darkstalkers",
    "Nil_Admirari_no_Tenbin:_Teito_Genwaku_Kitan_(TV)": "Nil_Admirari_Tenbin",
    "Ningen_Fushin_no_Boukensha-tachi_ga_Sekai_wo_Sukuu_You_Desu_(TV)": "Ningen_Fushin_Boukensha",
    "Ninja_to_Koroshiya_no_Futarigurashi,_Ninkoro_(TV)": "Ninja_Koroshiya_Ninkoro",
    "Nintama_Rantarou_Movie:_Ninjutsu_Gakuen_Zenin_Shutsudou!_no_Dan_(Movie)": "Nintama_Ninjutsu_Gakuen",
    "Noblesse_-_The_Beginning_of_Destruction_(OVA)": "Noblesse_Destruction",
    "Nobunaga_no_Shinobi:_Anegawa_Ishiyama-hen_(TV)": "Nobunaga_Shinobi_Anegawa",
    "Nobunaga_no_Shinobi:_Ise_Kanegasaki-hen_(TV)": "Nobunaga_Shinobi_Ise",
    "Nurse_Witch_Komugi_-_Return_to_Subject_Special_(Special)": "Nurse_Witch_Komugi_Return",
    "Nurse_Witch_Komugi-chan_Magikarte_Z_(OVA)": "Nurse_Witch_Komugi_Z",
        
    "Okinawa_de_Suki_ni_Natta_Ko_ga_Hougen_Sugite_Tsura_Sugiru_(TV)": "Okinawa_Hougen_Tsurai",
    "Omiai_Aite_wa_Oshiego,_Tsuyokina,_Mondaiji_(TV)": "Omiai_Oshiego_Mondaiji",
    "One_Piece_Movie_3_-_Chopper_and_the_Kingdom_of_Strange_Animals_(Movie)": "OP_Movie_3_Chopper",
    "One_Piece_Movie_6_-_Baron_Omatsuri_and_the_Secret_Island_(Movie)": "OP_Movie_6_Omatsuri",
    "One_Piece_Movie_8_-_Episode_of_Arabasta_-_The_Desert_Princess_and_the_Pirates_(Movie)": "OP_Movie_8_Arabasta",
    "One_Piece_Movie_9_-_Episode_of_Chopper_Plus_-_Bloom_in_the_Winter,_Miracle_Cherry_Blossom_(Movie)": "OP_Movie_9_Chopper_Plus",
    "Onii-chan_no_Koto_nanka_Zenzen_Suki_Janain_Dakara_ne!!_(TV)": "Onii-chan_Zenzen_Suki",
    "Onii-chan_Dakedo_Ai_Sae_Areba_Kankeinai_yo_ne!_(OniAi)_(TV)": "OniAi",
    "Ookami_to_Koushinryou:_Merchant_Meets_the_Wise_Wolf_(TV)": "Ookami_Koushinryou_Wolf",
    "Ore_dake_Level_Up_na_Ken_Season_2:_Arise_from_the_Shadow_(TV)": "Ore_Level_Up_2",
    "Ore_ga_Suki_nano_wa_Imouto_dakedo_Imouto_ja_Nai_(TV)": "Ore_Imouto_dakedo",
    "Ore_no_Imouto_ga_Konna_ni_Kawaii_Wake_ga_Nai_(TV)": "Oreimo",
    "Ore_no_Imouto_ga_Konna_ni_Kawaii_Wake_ga_Nai_2_(TV)": "Oreimo_2",
    "Ore_no_Kanojo_to_Osananajimi_ga_Shuraba_Sugiru_(OreShura)_(TV)": "OreShura",
    "Ore_no_N__nai_Sentakushi_ga,_Gakuen_Love_Come_o_Zenryoku_de_Jama_Shiteiru_(TV)": "Ore_no_Nai_Sentakushi",
    "Ore_no_Yubi_de_Midarero._Heitengo_Futarikiri_no_Salon_de_(TV)": "Ore_Yubi_Midarero",
    "Ore_wa_Subete_wo_Parry_suru:_Gyaku_Kanchigai_no_Sekai_Saikyou_wa_Boukensha_ni_Naritai_(TV)": "Ore_Parry_Saikyou",
    "Oretachi_ni_Tsubasa_wa_Nai_______under_the_innocent_sky_(TV)": "Oretachi_Tsubasa_Nai",
    "Osananajimi_ga_Zettai_ni_Makenai_Love_Comedy_(TV)": "Osananajimi_Makenai",
    "Oshiete_Mahou_no_Pendulum:_Rilu_Rilu_Fairilu_(TV)": "Rilu_Rilu_Fairilu",
    "Osomatsu-san_Movie:_Gekijou_Koukai_Kinen_-_Original_Tanpen_Gekijou_(ONA)": "Osomatsu_Movie_Tanpen",
    "Otome_Game_no_Hametsu_Flag_shika_Nai_Akuyaku_Reijou_ni_Tensei_shiteshimatta_(TV)": "HameFura",
    "Otome_Game_no_Hametsu_Flag_shika_Nai_Akuyaku_Reijou_ni_Tensei_shiteshimatta..._X_(TV)": "HameFura_X",
    "Otome_Game_Sekai_wa_Mob_ni_Kibishii_Sekai_desu_(TV)": "Otome_Game_Mob",
    "Otonari_no_Tenshi-sama_ni_Itsunomanika_Dame_Ningen_ni_Sareteita_Ken_(TV)": "Otonari_Tenshi",
    "Ouran_High_School_Host_Club_Live-Action_JDrama_(TV)": "Ouran_Live_JDrama",
    "Ouran_High_School_Host_Club_Live-Action_Movie_(Movie)": "Ouran_Live_Movie",
    "Overlord:_Ple_Ple_Pleiades_-_Clementine_the_Fugitive_(ONA)": "Overlord_Ple_Ple_Clem",
    
    "Party_kara_Tsuihou_sareta_Sono_Chiyushi,_Jitsu_wa_Saikyou_ni_Tsuki_(TV)": "Party_Tsuihou_Saikyou",
    "Pokemon_12th_Movie_Arceus_and_Jewel_Of_Liife_(Movie)": "Pokemon_12_Arceus",
    "Pokemon_Movie_08_-_Lucario_and_the_Mystery_of_Mew_(Movie)": "Pokemon_8_Lucario_Mew",
    "Pokemon_Movie_09_-_Pok__mon_Ranger_and_the_Temple_of_the_Sea_(Movie)": "Pokemon_9_Ranger",
    "Pokemon_Movie_11_-_Giratina_and_the_Sky_Warrior_(Movie)": "Pokemon_11_Giratina",
    "Pokemon_Movie_13_-_Zoroark:_Master_of_Illusions_(Movie)": "Pokemon_13_Zoroark",
    "Pokemon_Movie_15_-_Kyurem_vs._The_Sword_of_Justice_(Movie)": "Pokemon_15_Kyurem",
    "Pokemon_Movie_16_-_Genesect_and_The_Legend_Awaken_(Movie)": "Pokemon_16_Genesect",
    "Pokemon_Movie_17:_Hakai_no_Mayu_to_Diancie_(Movie)": "Pokemon_17_Diancie",
    "Pokemon_Movie_19:_Volcanion_to_Karakuri_no_Magearna_(Movie)": "Pokemon_19_Volcanion",
    "Pokemon_Movie_22:_Mewtwo_no_Gyakushuu_Evolution_(Movie)": "Pokemon_22_Mewtwo",
    "Pok__mon_the_Movie:_Black_-_Victini_and_Reshiram_(Movie)": "Pokemon_Black_Victini",
    "Pok__mon_the_Movie:_White_-_Victini_and_Zekrom_(Movie)": "Pokemon_White_Victini",
    "Precure_All_Stars_New_Stage:_Mirai_no_Tomodachi_(Movie)": "Precure_All_Stars_Mirai",
    "Prince_of_Tennis:_Another_Story_~Messages_From_Past_and_Future~_(OVA)": "PoT_Another_Story",
    "Prism_Magical_____PRISM_Generations!_(OVA)": "Prism_Magical_Generations",
    "Professor_Layton_and_the_Eternal_Diva_(Movie)": "Layton_Eternal_Diva",
    "Puss_in_Boots_3_-_Travels_Around_the_World_in_80_Days_(Movie)": "Puss_in_Boots_3",
    
    "Quiz_Magic_Academy_~The_Original_Animation~_(OVA)": "Quiz_Magic_Academy_OVA",
    
    "Re:Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season_(TV)": "ReZero_2",
    "Re:Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season_Part_2_(TV)": "ReZero_2_Part2",
    "Re:Zero_kara_Hajimeru_Isekai_Seikatsu_3rd_Season_(TV)": "ReZero_3",
    "Re:ZERO_kara_Hajimeru_Isekai_Seikatsu:_Shin_Henshuu-ban_(TV)": "ReZero_Shin_Henshuu",
    "Renmei_Kuugun_Koukuu_Mahou_Ongakutai_Luminous_Witches_(TV)": "Luminous_Witches",
    "Rikei_ga_Koi_ni_Ochita_no_de_Shoumei_shitemita._Heart_(TV)": "RikeKoi_Heart",
    "Rinne_no_Lagrange:_Flower_declaration_of_your_heart_(TV)": "Rinne_Lagrange_Flower",
    "Rokka_no_Yuusha:_Braves_of_the_Six_Flowers_(TV)": "Rokka_Yuusha",
    "Rokudenashi_Majutsu_Koushi_to_Akashic_Records_(TV)": "Rokudenashi_Akashic",
    "Rougo_ni_Sonaete_Isekai_de_8-manmai_no_Kinka_wo_Tamemasu_(TV)": "Rougo_Kinka",
    "Rur__ni_Kenshin_____Meiji_Kenkaku_Romantan_____Ishin_Shishi_e_no_Requiem_(TV)": "Rurouni_Requiem",
    "Rurouni_Kenshin:_Meiji_Kenkaku_Romantan_-_Kyoto_Douran_(TV)": "Rurouni_Kyoto",
    "Rurouni_Kenshin_-Meiji_Kenkaku_Romantan-_(2023)_(TV)": "Rurouni_2023",
    "Ryza_no_Atelier:_Tokoyami_no_Joou_to_Himitsu_no_Kakurega_(TV)": "Ryza_Atelier_Tokoyami",
    "Ry__gaj___Nanana_no_Maiz__kin_(TV)": "Nanana_Maizoukin",
    
    "S-Rank_Monster_no_Behemoth_Dakedo,_Neko_to_Machigawarete_Elf_Musume_no_Pet_Toshite_Kurashitemasu_(TV)": "Behemoth_Neko_Elf_Pet",
    "Saezuru_Tori_wa_Habatakanai:_The_Clouds_Gather_(Movie)": "Saezuru_Clouds_Gather",
    "Saijaku_Tamer_wa_Gomi_Hiroi_no_Tabi_wo_Hajimemashita_(TV)": "Saijaku_Tamer_Gomi_Hiroi",
    "Saihate_no_Paladin:_Tetsusabi_no_Yama_no_Ou_(TV)": "Saihate_Paladin_Tetsusabi",
    "Saikin,_Imouto_no_Yousu_ga_Chotto_Okashiinda_ga._(TV)": "Imouto_Yousu_Okashiinda",
    "Saikyou_no_Ousama,_Nidome_no_Jinsei_wa_Nani_wo_Suru_(TV)": "Saikyou_Ousama_Nidome",
    "Saikyou_no_Shienshoku_Wajutsushi_de_Aru_Ore_wa_Sekai_Saikyou_Clan_wo_Shitagaeru_(TV)": "Saikyou_Wajutsushi_Clan",
    "Saikyou_Tank_no_Meikyuu_Kouryaku:_Tairyoku_9999_no_Rare_Skill-mochi_Tank,_Yuusha_Party_wo_Tsuihou_sareru_(TV)": "Saikyou_Tank_Meikyuu",
    "Saint_Seiya:_Knights_of_the_Zodiac_-_Battle_for_Sanctuary_Part_2_(TV)": "Saint_Seiya_Sanctuary_2",
    "Saint_Seiya:_The_Hades_Chapter_-_Elysion_(OVA)": "Saint_Seiya_Elysion",
    "Saint_Seiya:_The_Hades_Chapter_-_Inferno_(OVA)": "Saint_Seiya_Inferno",
    "Saint_Seiya:_The_Hades_Chapter_-_Sanctuary_(OVA)": "Saint_Seiya_Sanctuary_OVA",
    "Sakura_no_Chikai:_Marronni_Yell_-_Higashi_no_Hichou_Shimotsuke-shi_wo_Yell!_(TV)": "Sakura_Chikai_Yell",
    "Sakura_Taisen_Sumire_Kanzaki_Intai_Kinen:_Su_Mi_Re_(OVA)": "Sakura_Taisen_Sumire",
    "Sakurako-san_no_Ashimoto_ni_wa_Shitai_ga_Umatteiru_(TV)": "Sakurako_Shitai_Umatteiru",
    "Salaryman_ga_Isekai_ni_Ittara_Shitennou_ni_Natta_Hanashi_(TV)": "Salaryman_Shitennou",
    "Sayonara_Ginga_Tetsudou_999:_Andromeda_Shuuchakueki_(Movie)": "Ginga_Tetsudou_Andromeda",
    "Scramble_Wars:_Tsuppashire!_Genom_Trophy_Rally_(OVA)": "Scramble_Wars_Genom",
    "Secret_Mission:_Sennyuu_Sousakan_wa_Zettai_ni_Makenai!_(TV)": "Secret_Mission_Sennyuu",
    "SD_Gundam_Sangokuden_Brave_Battle_Warriors_(TV)": "SD_Gundam_Sangokuden",
    "Seija_Musou:_Salaryman,_Isekai_de_Ikinokoru_Tame_ni_Ayumu_Michi_(TV)": "Seija_Musou_Salaryman",
    "Seiken_Densetsu:_Legend_of_Mana_-The_Teardrop_Crystal_(TV)": "Seiken_Densetsu_Teardrop",
    "Seijo_no_Maryoku_wa_Bannou_Desu_Season_2_(TV)": "Seijo_Maryoku_2",
    "Seikima_II_Humane_Society:_Jinrui_Ai_ni_Michita_Shakai_(OVA)": "Seikima_Humane_Society",
    "Seishun_Buta_Yarou_wa_Bunny_Girl_Senpai_no_Yume_wo_Minai_(TV)": "Bunny_Girl_Senpai",
    "Seitokai_no_Ichizon_-_Hekiyoh_Gakuen_Seitokai_Gijiroku_(TV)": "Seitokai_Ichizon_Hekiyoh",
    "Sekai_Saikou_no_Ansatsusha,_Isekai_Kizoku_ni_Tensei_suru_(TV)": "Sekai_Saikou_Ansatsusha",
    "Sengoku_Majin_Goushougun:_Toki_no_Etranger_(Movie)": "Sengoku_Majin_Etranger",
    "Senran_Kagura_Shinovi_Master:_Tokyo_Youma-hen_(TV)": "Senran_Kagura_Tokyo",
    "Seven_Knights_Revolution:_Eiyuu_no_Keishousha_(TV)": "Seven_Knights_Revolution",
    "Shijou_Saikyou_no_Daimaou,_Murabito_A_ni_Tensei_suru_(TV)": "Daimaou_Murabito_A",
    "SHIMONETA:_A_Boring_World_Where_the_Concept_of_Dirty_Jokes_Doesn___t_Exist_(TV)": "SHIMONETA",
    "Shin_no_Nakama_ja_Nai_to_Yuusha_no_Party_wo_Oidasareta_node,_Henkyou_de_Slow_Life_suru_Koto_ni_Shimashita_(TV)": "Shin_Nakama_Slow_Life",
    "Shin_no_Nakama_ja_Nai_to_Yuusha_no_Party_wo_Oidasareta_node,_Henkyou_de_Slow_Life_suru_Koto_ni_Shimashita_2nd_(TV)": "Shin_Nakama_Slow_Life_2",
    "Shin_Shinka_no_Mi:_Shiranai_Uchi_ni_Kachigumi_Jinsei_(TV)": "Shin_Shinka_no_Mi",
    "Shingeki_no_Kyojin:_The_Final_Season_-_The_Final_Chapters_(TV)": "Shingeki_Final_Chapters",
    "Shinka_no_Mi:_Shiranai_Uchi_ni_Kachigumi_Jinsei_(TV)": "Shinka_no_Mi",
    "Shinkansen_Henkei_Robo_Shinkalion_the_Animation_(TV)": "Shinkalion",
    "Shinkansen_Henkei_Robo_Shinkalion_Z_the_Animation_(TV)": "Shinkalion_Z",
    "Shinmai_Ossan_Boukensha,_Saikyou_Party_ni_Shinu_hodo_Kitaerarete_Muteki_ni_Naru_(TV)": "Shinmai_Ossan_Muteki",
    "Shirobuta_Kizoku_desu_ga_Zense_no_Kioku_ga_Haeta_node_Hiyoko_na_Otouto_Sodatemasu_(TV)": "Shirobuta_Kizoku",
    "Shokugeki_no_Souma:_San_no_Sara_-_Toutsuki_Ressha-hen_(TV)": "Shokugeki_Toutsuki",
    "Shouwa_Genroku_Rakugo_Shinjuu:_Sukeroku_Futatabi-hen_(TV)": "Rakugo_Sukeroku",
    "Shuumatsu_Nani_Shitemasu_ka__Isogashii_desu_ka__Sukutte_Moratte_Ii_desu_ka__(TV)": "Shuumatsu_Sukutte",
    "Slime_Taoshite_300-nen,_Shiranai_Uchi_ni_Level_Max_ni_Nattemashita_(TV)": "Slime_300_Max",
    "Slime_Taoshite_300-nen,_Shiranai_Uchi_ni_Level_Max_ni_Nattemashita_2nd_Season_(TV)": "Slime_300_Max_2",
    "Slime_Taoshite_300-nen,_Shiranai_Uchi_ni_Level_Max_ni_Nattemashita:_2nd_Season_(TV)": "Slime_300_Max_2nd",  
    "Sokushi_Cheat_ga_Saikyou_Sugite,_Isekai_no_Yatsura_ga_Marude_Aite_ni_(TV)": "Sokushi_Cheat_Saikyou",
    "sono_hanabira_ni_kuchizuke_o_-_anata_to_koibito_tsunagi_(OVA)": "Hanabira_Kuchizuke",
    "Sora_wo_Miageru_Shoujo_no_Hitomi_ni_Utsuru_Sekai_(TV)": "Sora_Miageru_Shoujo", 
    "Sore_Ike!_Anpanman:_Anpanman_to_Yukai_na_Nakama-tachi_(Movie)": "Anpanman_Nakama",
    "Sore_Ike!_Anpanman:_Hashire!_Wakuwaku_Anpanman_Grand_Prix_(Movie)": "Anpanman_Grand_Prix",
    "Sore_Ike!_Anpanman:_Kaiketsu_Naganegiman_to_Yakisobapanman_(Movie)": "Anpanman_Naganegiman",
    "Sore_Ike!_Anpanman:_Roll_to_Laura_Ukigumojou_no_Himitsu_(Movie)": "Anpanman_Laura",
    "Sore_Ike!_Anpanman:_Tekka_no_Maki-chan_to_Kin_no_Kamameshidon_(Movie)": "Anpanman_Maki_chan",
    "Soreyuke!_Uchuu_Senkan_Yamamoto_Yohko_(1999)_(TV)": "Uchuu_Senkan_Yohko",
    "Soukou_Kihei_Votoms:_Red_Shoulder_Document_-_Yabou_no_Roots_(OVA)": "Votoms_Red_Shoulder",
    "Soukyuu_no_Fafner:_Dead_Aggressor_-_Exodus_(TV)": "Fafner_Exodus",
    "Steins_Gate:_Kyoukaimenjou_no_Missing_Link_-_Divide_By_Zero_(OVA)": "Steins_Gate_Divide_Zero",
    "Stella_Womens_Academy,_High_School_Division_Class_C3_(TV)": "Stella_C3",
    "Suki_ni_Naru_Sono_Shunkan_wo:_Kokuhaku_Jikkou_Iinkai_(Movie)": "Suki_Naru_Kokuhaku",
    "Sumeba_Miyako_no_Cosmos-sou_Suttoko_Taisen_Dokkoida_(TV)": "Cosmos_Dokkoida",
    "Super_Robot_Wars_Original_Generation_-_The_Animation_(OAV)_(OVA)": "SRW_OG_Animation",
    "Superdimensional_Romanesque_Samy_-_Missing_99_(OVA)": "Samy_Missing_99",
    "Sword_Art_Online_Alternative:_Gun_Gale_Online_(TV)": "SAO_GGO",
    "Sword_Art_Online_Alternative:_Gun_Gale_Online_II_(TV)": "SAO_GGO_2",
    "Sword_Art_Online_the_Movie:_Ordinal_Scale_(Movie)": "SAO_Ordinal_Scale",
    "Sword_Art_Online:_Alicization_-_War_of_Underworld_(TV)": "SAO_War_Underworld",
        
    "Taishou_Itsuwari_Bridal:_Migawari_Hanayome_to_Gunpuku_no_Mouai_(TV)": "Taishou_Itsuwari_Bridal",
    "Tales_of_Crestoria:_Toga_Waga_wo_Shoite_Kare_wa_Tatsu_(Special)": "Tales_Crestoria_Toga",
    "Tales_of_Symphonia_The_Animation:_Sekai_Tougou-hen_(OVA)": "Tales_Symphonia_Tougou",
    "Tatoeba_Last_Dungeon_Mae_no_Mura_no_Shounen_ga_Joban_no_Machi_de_Kurasu_Youna_Monogatari_(TV)": "Last_Dungeon_Shounen",
    "Tearmoon_Teikoku_Monogatari:_Dantoudai_kara_Hajimaru,_Hime_no_Tensei_Gyakuten_Story_(TV)": "Tearmoon_Teikoku",
    "Tenchi_Muyou!:_Galaxy_Police_Mihoshi_Space_Adventure_(OVA)": "Tenchi_Mihoshi",
    "Tensei_Kenja_no_Isekai_Life_~Dai-2_no_Shokugyou_wo_Ete,_Sekai_Saikyou_ni_Narimashita~_(TV)": "Tensei_Kenja_Isekai",
    "Tensei_Kizoku_no_Isekai_Boukenroku:_Jichou_wo_Shiranai_Kamigami_no_Shito_(TV)": "Tensei_Kizoku_Boukenroku",
    "Tensei_shitara_Dainana_Ouji_Datta_node,_Kimama_ni_Majutsu_wo_Kiwamemasu_(TV)": "Tensei_Dainana_Ouji",
    "Tensura_Nikki:_Tensei_shitara_Slime_Datta_Ken_(TV)": "Tensura_Nikki",
    "Tesagure_Bukatsumono_Spin-off_Purupurun_Sharumu_to_Asobou_(TV)": "Tesagure_Sharumu",
    "Tezuka_Osamu_ga_Kieta_!_20_Seiki_Saigo_no_Kaijiken_(Special)": "Tezuka_Kaijiken",
    "Tezuka_Osamu_no_Kyuuyaku_Seisho_Monogatari:_In_the_Beginning_(TV)": "Tezuka_Seisho",
    "The_Fantastic_Flying_Books_of_Mr.Morris_Lessmore_(2011)_(Movie)": "Morris_Lessmore",
    "The_iDOLM_STER_Movie:_Kagayaki_no_Mukougawa_e!_(Movie)": "iDOLM_STER_Movie",
    "The_Jungle_Was_Always_Nice_The_Came_Guu_Final_(OVA)": "Jungle_Guu_Final",
    "The_Jungle_was_Always_Nice_then_Along_Came_Guu_(TV)": "Jungle_Guu",
    "The_Jungle_was_Always_Nice_then_Along_Came_Guu_Deluxe_(TV)": "Jungle_Guu_Deluxe",
    "The_Legend_of_Heroes:_Sen_no_Kiseki_-_Northern_War_(TV)": "Sen_no_Kiseki_Northern",
    "The_Legend_of_Heroes:_Trails_in_The_Sky_(Special)": "Trails_in_Sky",
    "The_Moon_-_Tsuki_ga_Hoshii_to___jo-sama_ga_Naita_(Movie)": "Moon_Tsuki_Hoshii",
    "The_New_Fist_of_the_North_Star:_Kens_Revenge_(OVA)": "Fist_North_Star_Revenge",
    "The_Prince_of_Tennis:_Two_Samurais,_The_First_Game_(Movie)": "PoT_Two_Samurais",
    "The_Prince_of_Tennis_II_U-17_World_Cup_Semifinal_(TV)": "PoT_U17_Semifinal",
    "The_World_Only_God_Know:Magical_Star_Kanon_100__(OVA)": "TWOGK_Kanon",
    "The_World_Only_God_Knows_III:_Goddesses_Arc_(TV)": "TWOGK_Goddesses",
    "Time_Travel_Shoujo:_Mari_Waka_to_8-nin_no_Kagakusha-tachi_(TV)": "Time_Travel_Shoujo",
    "To_aru_Majutsu_no_Index_-_Endymion_no_Kiseki_(Movie)": "Index_Endymion",
    "Toaru_Hikuushi_e_no_Tsuioku_-_The_Princess_and_the_Pilot_(Movie)": "Hikuushi_Princess",
    "Tobidasu_PriPara:_Mi~nna_de_Mezase!_Idol___Grand_Prix_(Movie)": "PriPara_Grand_Prix",
    "Tokidoki_Bosotto_Russia-go_de_Dereru_Tonari_no_Alya-san_(TV)": "Tokidoki_Alya_san",
    "Toku:_Touken_Ranbu_-_Hanamaru_-_Setsugetsuka_(Movie)": "Touken_Ranbu_Setsugetsuka",
    "Tokyo_Majin_Gakuen_Kenpuchou_Tou_Dai_Ni_Maku_(TV)": "Tokyo_Majin_Dai_Ni",
    "Tomica_Hyper_Rescue_Drive_Head:_Kidou_Kyuukyuu_Keisatsu_(TV)": "Tomica_Drive_Head",
    "Touyama_Sakura_Uchuu_Chou:_Yatsu_no_Na_wa_Gold_(OVA)": "Touyama_Sakura_Gold",
    "Trickster:_Edogawa_Ranpo_Shounen_Tanteidan_Yori_(TV)": "Trickster_Ranpo",
    "Tsubasa_RESERVoir_CHRoNiCLE_the_Movie:_The_Princess_in_the_Birdcage_Kingdom_(Movie)": "Tsubasa_Birdcage",
    "Tsuki_ga_Michibiku_Isekai_Douchuu_2nd_Season_(TV)": "Tsuki_Michibiku_2",
    "Tsundere_Akuyaku_Reijou_Lieselotte_to_Jikkyou_no_Endou-kun_to_Kaisetsu_no_Kobayashi-san_(TV)": "Tsundere_Lieselotte",
    "Tsuujou_Kougeki_ga_Zentai_Kougeki_de_Ni-kai_Kougeki_no_Okaasan_wa_Suki_Desu_ka_(TV)": "Tsuujou_Kougeki_Okaasan",
        
    "UFO_Ultramaiden_Valkyrie_2:_December_Nocturne_(TV)": "UFO_Valkyrie_2",
    "Uchuu_Senkan_Yamato_2202:_Ai_no_Senshi-tachi_(OVA)": "Yamato_2202",
    "Uchiage_Hanabi,_Shita_kara_Miru_ka__Yoko_kara_Miru_ka__(Movie)": "Uchiage_Hanabi",
    "Uchi_no_Ko_no_Tame_naraba,_Ore_wa_Moshikashitara_Maou_mo_Taoseru_kamo_Shirenai_(TV)": "Uchi_no_Ko_Maou",
    "Uchi_no_Kaisha_no_Chiisai_Senpai_no_Hanashi_(TV)": "Chiisai_Senpai",
    "Ultra_Nyan:_Hoshizora_kara_Maiorita_Fushigi_Neko_(Movie)": "Ultra_Nyan",
    "Ultraman_Kids:_Haha_wo_Tazunete_3000-man_Kounen_(TV)": "Ultraman_Kids",
    "Ulysses:_Jehanne_Darc_to_Renkin_no_Kishi_(TV)": "Ulysses_Jehanne",
    "Uma_Musume:_Pretty_Derby_-_Shinjidai_no_Tobira_(TV)": "Uma_Musume_Tobira",
    "Umi_Monogatari_~Anata_ga_Ite_Kureta_Koto~_(TV)": "Umi_Monogatari",
    "Urotsukid__ji_II:_Legend_of_the_Demon_Womb_(OVA)": "Urotsukidoji_2",
    "Urotsukid__ji_III:_Return_of_the_Overfiend_(OVA)": "Urotsukidoji_3",
    "Uta_no_Prince-sama_-_Maji_Love_3000__Revolutions_(TV)": "UtaPri_Maji_3000",
    "Uta_no___Prince-sama____Maji_Love_ST___RISH_Tours_~Tabi_no_Hajimari~_(TV)": "UtaPri_RISH_Tours",


    
    
    "Vigilante:_Boku_no_Hero_Academia_Illegals_(TV)": "Vigilante_Illegals",
    "Visionaries_Knights_of_the_Magical_Light_(TV)":"Visionaries_Knight",
    "VTuber_Nanda_ga_Haishin_Kiri_Wasuretara_Densetsu_ni_Natteta_(TV)": "VTuber_Nanda",

    "Why_Raeliana_Ended_Up_at_the_Dukes_Mansion_(TV)": "Raeliana_Duke",
    "World_Destruction:_Sekai_Bokumetsu_no_Rokunin_(TV)": "World_Destruction",
    "Watashi,_Nouryoku_wa_Heikinchi_de_tte_Itta_yo_ne!_(TV)": "Watashi_Heikinchi",
    "Watashi_no_Coffee_Samurai:_Jihanki-teki_na_Kareshi_(Special)": "Coffee_Samurai",
    "Watashi_ga_Motenai_no_wa_Dou_Kangaete_mo_Omaera_ga_Warui!_(TV)": "Watamote",

    
    "xxxHOLiC_The_Movie:_A_Midsummer_Nights_Dream_(Movie)": "xxxHoLic_Midsummer",

    "Yahari_Ore_no_Seishun_Love_Come_wa_Machigatteiru_(TV)": "Oregairu",
    "Yahari_Ore_no_Seishun_Love_Come_wa_Machigatteiru._Zoku_(TV)": "Oregairu_Zoku",
    "Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru._Kan_(TV)": "Oregairu_Kan",
    "Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru._Zoku_(TV)": "Oregairu_Zoku_2",
    "Yamato_Nadeshiko_Shichi_Henge_Live-Action_JDrama_(TV)": "Yamato_Nadeshiko_JDrama",
    "Yarinaoshi_Reijou_wa_Ryuutei_Heika_wo_Kouryakuchuu_(TV)": "Yarinaoshi_Reijou",
    "Yawaraka_Sangokushi_Tsukisase!!_Ryofuko-chan_(TV)": "Yawaraka_Sangokushi",
    "Yokohama_Kaidashi_Kikou:_Quiet_Country_Cafe_(OVA)": "Yokohama_Kaidashi",
    "Youre_Under_Arrest_2nd_Season_Fast___Furious_(TV)": "Youre_Under_Arrest_2",
    "Youkai_Watch_Jam:_Youkai_Gakuen_Y_-_N_to_no_Souguu_(TV)": "Youkai_Watch_Jam",
    "Youkai_Watch_Movie_1:_Tanjou_no_Himitsu_da_Nyan!_(Movie)": "Youkai_Watch_1",
    "Youkai_Watch_Movie_2:_Enma_Daiou_to_Itsutsu_no_Monogatari_da_Nyan!_(Movie)": "Youkai_Watch_2",
    "Youkai_Watch_Movie_3:_Soratobu_Kujira_to_Double_Sekai_no_Daibouken_da_Nyan!_(Movie)": "Youkai_Watch_3",
    "Youkai_Watch_Movie_4:_Shadow_Side_-_Oni-ou_no_Fukkatsu_(Movie)": "Youkai_Watch_4",
    "Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_(TV)": "Classroom_Elite",
    "Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_2nd_Season_(TV)": "Classroom_Elite_2",
    "Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_3rd_Season_(TV)": "Classroom_Elite_3",
    "Yowai_5000-nen_no_Soushoku_Dragon,_Iwarenaki_Jaryuu_Nintei_(TV)": "5000nen_Dragon",
    "Yowai_5000-nen_no_Soushoku_Dragon,_Iwarenaki_Jaryuu_Nintei_2nd_Season_(TV)": "5000nen_Dragon_2",
    "Ys:_Tenkuu_no_Shinden_-_Adol_Christine_no_Bouken_(OVA)": "Ys_Adol_Christine",
    "Yu-Gi-Oh!_5Ds_-_OVA_-_Evolving_Duel!_Stardust_vs_Red_Demon_(OVA)": "YG0_5Ds_Stardust",
    "Yume_Kakeru_Kougen:_Kiyosato_no_Chichi_Paul_Rusch_(Movie)": "Yume_Kakeru_Kougen",
    "Yume_Oukoku_to_Nemureru_100_Nin_no_Ouji-sama_(TV)": "100_Ouji-sama",
    "Yume_Oukoku_to_Nemureru_100_Nin_no_Ouji-sama:_Short_Stories_(TV)": "100_Ouji-sama_Shorts",
    "Y__sha_ni_Narenakatta_Ore_wa_Shibushibu_Sh__shoku_o_Ketsui_Shimashita_(TV)": "Yuusha_Narenakatta",
    "Yuuki_Yuuna_wa_Yuusha_de_Aru:_Dai_Mankai_no_Shou_(TV)": "YuYuYu_Dai_Mankai",
    "Yuuki_Yuuna_wa_Yuusha_de_Aru:_Washio_Sumi_no_Shou_(TV)": "YuYuYu_Washio",
    "Yuuki_Yuuna_wa_Yuusha_de_Aru:_Yuusha_no_Shou_(TV)": "YuYuYu_Yuusha",
    
    "Zetsuen_no_Tempest:_The_Civilization_Blaster_(TV)": "Zetsuen_no_Tempest_Blaster",
    "Zettai_Karen_Children_OVA:_Aitazousei!_Ubawareta_Mirai__(TV)": "Zettai_Karen",
    "Zettai_Karen_Children:_The_Unlimited_Hyoubu_Kyousuke_(TV)": "Zettai_Karen_Children",
    "Zom_100:_Zombie_ni_Naru_made_ni_Shitai_100_no_Koto_(TV)": "Zom_100_Shitai",
    "Zutto_Mae_Kara_Suki_Deshita.:_Kokuhaku_Jikkou_Iinkai_(Movie)": "Zutto_Mae_Kara",

    "Saikyou_no_Ousama,_Nidome_no_Jinsei_wa_Nani_wo_Suru_(TV)": "Tbate",

    
}

mappingrev = {
    #-------------AAAAAAAAAAAAAAAAAAAAA-------------------#
    "A=rank": "A-Rank_Party_wo_Ridatsu_shita_Ore_wa,_Moto_Oshiego-tachi_to_Meikyuu_Shinbu_wo_Mezasu_(TV)",
    "Active_Raid_S2": "Active_Raid:_Kidou_Kyoushuushitsu_Dai_Hachi_Gakari_2nd_(TV)",
    "Akuyaku_Reijou_Level_99": "Akuyaku_Reijou_Level_99:_Watashi_wa_Ura-Boss_desu_ga_Maou_dewa_Arimasen_(TV)",
    "Alice_in_the_Country": "Alice_in_the_Country_of_Hearts:_Wonderful_Wonder_World_(Movie)",
    "Ancien_to_Mahou": "Ancien_to_Mahou_no_Tablet:_Mou_Hitotsu_no_Hirune_Hime_(ONA)",
    "Ane_Log": "Ane_Log:_Moyako_Neesan_no_Honpen_wo_Tobidashite_Tomaranai_Monologue_(TV)",
    "Araiso_Private": "Araiso_Private_High_School_Student_Council_Executive_Committee_(OVA)",
    "Ateuma_Chara": "Ateuma_Chara_no_Kuse_Shite,_Spadali_Oji_ni_Chouai_Sarete_Imasu_(TV)",

    #-------------BBBBBBBBBBBBBBBBBBB-------------------#
    "Bishoujo_Senshi_Death": "Bishoujo_Senshi_Sailor_Moon_Crystal:_Death_Busters-hen_(TV)",
    "Boruto_Movie_Hokage": "Boruto:_Naruto_the_Movie_-_Naruto_ga_Hokage_ni_Natta_Hi_(Special)",
    "Botsuraku": "Botsuraku_Yotei_no_Kizoku_dakedo,_Hima_datta_kara_Mahou_wo_Kiwametemita_(TV)",
    "Boukensha_ni_Naritai": "Boukensha_ni_Naritai_to_Miyako_ni_Deteitta_Musume_ga_S-Rank_ni_Natteta_(TV)",
    "Buddy_Complex_Special": "Buddy_Complex:_Kanketsu-hen_-_Ano_Sora_ni_Kaeru_Mirai_de_(Special)",
    "Buta_no_Gotaku": "Buta_no_Gotoki_Sanzoku_ni_Torawarete_Shojo_wo_Ubawareru_Kyonyuu_Himekishi___Onna_Senshi_(TV)",
    #------------CCCCCCCCCCCCCCCCCCCCCC-------------------#
    "Cheat_Drugstore": "Cheat_Kusushi_no_Slow_Life:_Isekai_ni_Tsukurou_Drugstore_(TV)",
    "Chiba_pedal_Anzen": "Chiba_Pedal:_Yowamushi_Pedal_to_Manabu_Jitensha_Koutsuu_Anzen_(ONA)",
    "Chiisana_Ahiru": "Chiisana_Ahiru_no_Ooki_na_Ai_no_Monogatari:_Ahiru_no_Kwak_(TV)",
    "Chiisana_Monogatari": "Chiisana_Koi_no_Monogatari:_Chichi_to_Sally_Hatsukoi_no_Shiki_(Special)",
    "Choujin_Koukousei": "Choujin_Koukousei_tachi_wa_Isekai_demo_Yoyuu_de_Ikinuku_you_desu!_(TV)",
    "City_hunter_Saeba": "City_Hunter:_Kinkyuu_Namachuukei!__Kyouakuhan_Saeba_Ryou_no_Saigo_(Special)",
    "Corpse_Party_Souls": "Corpse_Party:_Tortured_Souls_-_Bougyakusareta_Tamashii_no_Jukyou_(OVA)",
    #------------DDDDDDDDDDDDDDDDDDDDD-------------------#
    "Danganronpa_3_Kibou_hen": "Danganronpa_3:_The_End_of_Kibougamine_Gakuen_-_Kibou-hen_(Special)",
    "Danganronpa_Zetsubou_hen": "Danganronpa_3:_The_End_of_Kibougamine_Gakuen_-_Zetsubou-hen_(TV)",
    "Danganronpa_Mirai_hen": "Danganronpa_3:_The_End_of_Kibougamine_Gakuen_____Mirai-hen_(TV)",
    "Danganronpa_The_Animation": "Danganronpa:_Kibou_no_Gakuen_to_Zetsubou_no_Koukousei_-_The_Animation_(TV)",
    "Darker_than_BLACK_kuro": "Darker_than_BLACK:_Kuro_no_Keiyakusha_Gaiden_(TV)",
    "Death_March_kara_Hajimaru": "Death_March_kara_Hajimaru_Isekai_Kyousoukyoku_(TV)",
    "Dekisokonai_Yobareta": "Dekisokonai_to_Yobareta_Motoeiyuu_wa_Jikka_kara_Tsuihou_sareta_node_Sukikatte_ni_Ikiru_Koto_ni_Shita_(TV)",
    "Dengeki_Oshioki_Battle": "Dengeki_Oshioki_Musume_Gootaman_R:_Ai_to_Kanashimi_no_Final_Battle_(OVA)",
    "Dengeki_Gootaman": "Dengeki_Oshioki_Musume_Gootaman:_Gootaman_Tanjou-hen_(OVA)",
    "Detective_Conan_Mov_06": "Detective_Conan_Movie_06:_The_Phantom_of_Baker_Street_(Movie)",
    "Detective_Conan_Mov_08": "Detective_Conan:_Magician_of_the_Silver_Sky_(movie_8)_(Movie)",
    "Detective_Conan_Mov_09": "Detective_Conan:_Strategy_Above_the_Depths_(movie_9)_(Movie)",
    "Detective_Conan_Mov_21": "Detective_Conan:_The_Crimson_Love_Letter_(movie_21)_(Movie)",
    "Detective_Conan_Mov_20": "Detective_Conan:_The_Darkest_Nightmare_(movie_20)_(Movie)",
    "Detective_Conan_Mov_10": "Detective_Conan:_The_Private_Eyes_Requiem_(movie_10)_(Movie)",
    "Digimon_Xros_Shonen": "Digimon_Xros_Wars:_Toki_o_Kakeru_Sh__nen_Hunter-tachi_(TV)",
    "Dorami_Doraemon_Robot": "Dorami___Doraemons:_Robot_Schools_Seven_Mysteries_(Movie)",
    "Druaga_Jil": "Druaga_no_Tou:_The_Aegis_of_Uruk_-_Jil_no_Bouken_(Special)",
    "Danmachi": "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_(TV)",
    "Danmachi_Sword": "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_Gaiden:_Sword_Oratoria_(TV)",
    "Danmachi_2": "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_II_(TV)",
    "Danmachi_4": "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_IV:_Shin_Shou_-_Meikyuu-hen_(TV)",
    "Danmachi_5": "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka_V:_Houjou_no_Megami-hen_(TV)",
    "Danmachi_Fuka": "Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_no_Darou_ka_IV:_Fuka_Shou_-_Yakusai-hen_(TV)",
    
    #-----------EEEEEEEEEEEEEEEEEEEEEEEE------------------#
    
    "Ebisugawa_Club": "Ebisugawa_Public_High_School_Astronomical_Club_(TV)",
    "Ebiten_Koukou":"Ebiten:_Kouritsu_Ebisugawa_Koukou_Tenmonbu_(ONA)",
    "Eiga_Kuma_Sweets": "Eiga_Kuma_no_Gakkou:_Patissier_Jackie_to_Ohisama_no_Sweets_(Movie)",
    "Eiga_Precure": "Eiga_Precure_All_Stars_DX3:_Mirai_ni_Todoke!_Sekai_wo_Tsunagu_Niji-iro_no_Hana_(Movie)",
    "Eiyuuou_Tame_Sekai": "Eiyuuou,_Bu_wo_Kiwameru_Tame_Tenseisu._Soshite,_Sekai_Saikyou_no_Minarai_Kishi_(TV)",
    "Embracing_Love_Spring": "Embracing_Love:_Cherished_Spring_(Haru_wo_Daiteita)_(OVA)",
    "Escha_no_Sora": "Escha___Logy_no_Atelier:_Tasogare_no_Sora_no_Renkinjutsushi_(TV)",
    "Eureka_Seven_ov": "Eureka_Seven_AO:_Jungfrau_no_Hanabanatachi_(OVA)",


    #-----------FFFFFFFFFFFFFFFFFFFFFFFF-----------------#
    "Fairy_Ranmaru_Anata": "Fairy_Ranmaru:_Anata_no_Kokoro_Otasuke_Shimasu_(TV)",
    "Fate_Grand_order_Babylonia": "Fate_Grand_Order:_Zettai_Majuu_Sensen_Babylonia_(TV)",
    "Final_Fantasy_VII_Denzel": "Final_Fantasy_VII_:_On_the_Way_to_A_Smile_Episode_Denzel_(TV)",
    "Final_Fantasy_VII_Cerberus": "Final_Fantasy_VII_-_Dirge_Of_Cerberus_CG_Movies_(Movie)",
    "Tbate": "Saikyou_no_Ousama,_Nidome_no_Jinsei_wa_Nani_wo_Suru_(TV)",
    "Fortune_Quest_Boukensha": "Fortune_Quest:_Yo_ni_mo_Shiawase_na_Boukensha-tachi_(OVA)",
    "Fuguushoku_Kanteishi_Saikyou": "Fuguushoku__Kanteishi__ga_Jitsuwa_Saikyou_Datta:_Naraku_de_Kitaeta_Saikyou_no__Shingan__de_Musousuru_(TV)",
    "Full_Moon_Cute_Cute": "Full_Moon_O_Sagashite:_Cute_Cute_Adventure_(Special)",
    "Futsuu_Joshikousei_Locodol": "Futsuu_no_Joshikousei_ga__Locodol__Yatte_Mita_(TV)",

    #-----------GGGGGGGGGGGGGGGGGGGGGGGGGGGGG----------------#
    "Gekijouban_Gintama_Yorozuya": "Gekijouban_Gintama_Kanketsu-hen:_Yorozuya_yo_Eien_Nare_(Movie)",
    "Gekijouban_Torika_Spe": "Gekijouban_Toriko_Bishokushin_no_Special_Menu_(Movie)",
    "Gaikotsu_Tadaima_Isekai": "Gaikotsu_Kishi-sama,_Tadaima_Isekai_e_Odekakechuu_(TV)",
    "Genjitsu_Shugi_Yuusha_Part_2": "Genjitsu_Shugi_Yuusha_no_Oukoku_Saikenki_Part_2_(TV)",
    "Geobreeders_2_Toppa": "Geobreeders_2:_Mouryou_Yuugekitai_File-XX_Ransen_Toppa_(OVA)",
    "Ghost_in_the_Shell_Architecture": "Ghost_in_the_Shell_Arise:_Alternative_Architecture_(TV)",
    "Ghost_in_the_Shell_Solid": "Ghost_in_the_Shell:_S.A.C._Solid_State_Society_(Movie)",
    "Ginga_Eiyuu_Kaikou": "Ginga_Eiyuu_Densetsu:_Die_Neue_These_-_Kaikou_(TV)",
    "Ginga_Eiyuu_Sakubou": "Ginga_Eiyuu_Densetsu:_Die_Neue_These_-_Sakubou_(TV)",
    "Gorilla_no_Kami": "Gorilla_no_Kami_kara_Kagosareta_Reijou_wa_Ouritsu_Kishi-dan_de_Kawaigarareru_(TV)",
    "Guild_no_Uketsukejou": "Guild_no_Uketsukejou_desu_ga,_Zangyou_wa_Iya_nano_de_Boss_wo_Solo_Toubatsu_Shiyou_to_Omoimasu_(TV)",
    "Gyakuten_Saiban": "Gyakuten_Saiban:_Sono_Shinjitsu,_Igi_Ari!_(TV)",
    "Gyakuten_Saiban_2": "Gyakuten_Saiban:_Sono_Shinjitsu,_Igi_Ari!_Season_2_(TV)",

    #-----------HHHHHHHHHHHHHHHHHHHHH----------------#

    "Hanayaka_Nari": "Hanayaka_Nari,_Waga_Ichizoku:_Kinetograph_(OVA)",
    "Hanyou_no_Sengoku": "Hanyou_no_Yashahime:_Sengoku_Otogizoushi_-_Ni_no_Shou_(TV)",
    "Harukanaru_Toki_ov": "Harukanaru_Toki_no_Naka_de:_Ajisai_Yumegatari_(OVA)",
    "Harukanaru_Toki_2_ov": "Harukanaru_Toki_no_Naka_de_2:_Shiroki_Ryuu_no_Miko_(OVA)",
    "Harukanaru_Toki_3_sp": "Harukanaru_Toki_no_Naka_de_3:_Owarinaki_Unmei_(Special)",
    "Harukanaru_Toki_3_kurenai": "Harukanaru_Toki_no_Naka_de_3:_Kurenai_no_Tsuki_(Special)",
    "Honzuki_3": "Honzuki_no_Gekokujou:_Shisho_ni_Naru_Tame_ni_wa_Shudan_wo_Erandeiraremasen_3rd_Season_(TV)",
    "Hayate_2012": "Hayate_no_Gotoku_(2012):_Can___t_Take_My_Eyes_Off_You_(TV)",
    "Hazure_Skill": "Hazure_Skill_Kinomi_Master:_Skill_no_Mi_(Tabetara_Shinu)_wo_Mugen_ni_Taberareru_You_ni_Natta_Ken_ni_Tsuite_(TV)",
    "Hazurewaku_no_Joutai": "Hazurewaku_no_Joutai_Ijou_Skill_de_Saikyou_ni_Natta_Ore_ga_Subete_wo_Juurin_suru_made_(TV)",
    "Hengen_Taima": "Hengen_Taima_Yakou_Karura_Mau!_Nara_Onryou_Emaki_(Movie)",
    "Hengen_Taima_Yakou": "Hengen_Taima_Yakou_Karura_Mau!_Sendai_Kokeshi_Enka_(OVA)",
    "Heroine_Tarumono!_Kirawara": "Heroine_Tarumono!_Kiraware_Heroine_to_Naisho_no_Oshigoto_(TV)",
    "Hifuu_Katsudou": "Hifuu_Katsudou_Kiroku:_The_Sealed_Esoteric_History_(OVA)",
    "Higeki_no_Genkyou": "Higeki_no_Genkyou_to_Naru_Saikyou_Gedou_Last_Boss_Joou_wa_Tami_no_Tame_ni_Tsukushimasu_(TV)",
    "Highschool_dead": "Highschool_of_the_Dead:_Drifters_of_the_Dead_(OVA)",
    "Hitomi_Shounen": "Hitomi_no_Naka_no_Shounen:_Juugo_Shounen_Hyouryuuki_(Special)",
    "Honzuki_Shudan": "Honzuki_no_Gekokujou:_Shisho_ni_Naru_Tame_ni_wa_Shudan_wo_Erandeiraremasen_(TV)",
    "Honzuki_Shudan_2nd": "Honzuki_no_Gekokujou:_Shisho_ni_Naru_Tame_ni_wa_Shudan_wo_Erandeiraremasen_2nd_Season_(TV)",
    "Hoshi_ni_Negai": "Hoshi_ni_Negai_wo:_Cold_Body___Warm_Heart_(ONA)",
    "Hypnosis_Mic": "Hypnosis_Mic:_Division_Rap_Battle_-_Rhyme_Anima___(TV)",
    "Hayate_gotoku!": "Hayate_no_Gotoku!_Heaven_Is_a_Place_on_Earth_(Movie)",
    "Hataraku_Otona": "Hataraku_Otona_no_Renai_Jijou_The_Animation_(OVA)",

    #-----------IIIIIIIIIIIIIIIIIIIII----------------#
    "Reincarnated_7th_Prince": "I_Was_Reincarnated_as_the_7th_Prince_So_I_Can_Take_My_Time_Perfecting_My_Magical_Ability_(TV)",
    "Ikeman_sengoku": "Ikemen Sengoku: Toki wo Kakeru ga Koi wa Hajimaranai (TV)",
    "Inferious_Wakusei": "Inferious_Wakusei_Senshi_Gaiden_Condition_Green_(OVA)",
    "Interstella_555": "Inu_to_Neko_Docchimo_Katteru_to_Mainichi_Tanoshii_(TV)",
    "InuYasha_Looking_Glass": "InuYasha_Movie_2_-_Castle_Beyond_the_Looking_Glass_(Movie)",
    "InuYasha_Across_Time": "InuYasha_the_Movie_1_-_Affections_Touching_Across_Time_(Movie)",
    "InuYasha_Hoorable_Ruler": "InuYasha_the_Movie_3:_Swords_of_an_Honorable_Ruler_(Movie)",
    "Isekai_de_Cheat_Skill": "Isekai_de_Cheat_Skill_wo_Te_ni_Shita_Ore_wa,_Genjitsu_Sekai_wo_mo_Musou_Suru:_Level_Up_wa_Jinsei_wo_Kaeta_(TV)",
    "Isekai_Mofumofu": "Isekai_de_Mofumofu_Nadenade_suru_Tame_ni_Ganbattemasu_(TV)",
    "Isekai_Izakaya_Nobu": "Isekai_Izakaya:_Koto_Aitheria_no_Izakaya_Nobu_(TV)",
    "Isekai_Maou_Dorei": "Isekai_Maou_to_Shoukan_Shoujo_no_Dorei_Majutsu_(TV)",
    "Isekai_Maou_dorei_2": "Isekai_Maou_to_Shoukan_Shoujo_no_Dorei_Majutsu____(TV)",
    "Isekai_Yururi_Shimasu": "Isekai_Yururi_Kikou:_Kosodateshinagara_Boukensha_Shimasu_(TV)",
    "Isho_ni_Training_Hinako": "Issho_ni_Training_Ofuro_Bathtime_with_Hinako___Hiyoko_(OVA)",
    "Isshun_Chiyushi": "Isshun_de_Chiryoushiteita_no_ni_Yakudatazu_to_Tsuihousareta_Tensai_Chiyushi,_Yami_Healer_Toshite_Tanoshiku_Ikiru_(TV)",
    "Itai_Shitai_Omaimasu": "Itai_no_wa_Iya_nano_de_Bougyoryoku_ni_Kyokufuri_Shitai_to_Omoimasu_(TV)",
    "Itai_Shitai_Omaimasu_2": "Itai_no_wa_Iya_nano_de_Bougyoryoku_ni_Kyokufuri_Shitai_to_Omoimasu._2_(TV)",
    "Iya_na_Misete": "Iya_na_Kao_sare_nagara_Opantsu_Misete_Moraitai_(ONA)",
    "Iya_na_Misete_2": "Iya_na_Kao_sare_nagara_Opantsu_Misete_Moraitai_2_(ONA)",

    #-----------JJJJJJJJJJJJJJJJJJJJJJJJJJJJ---------------#
    "Janguru": "Janguru_wa_Itsumo_Hale_nochii_Guu_Deluxe_(TV)",
    "Jidou_Hanbaiki": "Jidou_Hanbaiki_ni_Umarekawatta_Ore_wa_Meikyuu_wo_Samayou_(TV)",
    "jimihen_Jun_Isei": "Jimihen!!:_Jimiko_wo_Kaechau_Jun_Isei_Kouyuu!!_(TV)",
    "Jojos_6_Ocean": "JoJos_Bizarre_Adventure_Part_6:_Stone_Ocean_(TV)",
    "JoJo_Diamond_Kudakenai": "JoJo_no_Kimyou_na_Bouken:_Diamond_wa_Kudakenai_(TV)",
    "Jojos_Stardust_Crusaders": "JoJos_Bizarre_Adventure:_Stardust_Crusaders_(TV)",
    "Joshiochi": "Joshiochi!:_2-kai_kara_Onnanoko_ga..._Futtekita!__(TV)",
    "Jubei_chan_2": "Jubei-chan_2:_The_Counterattack_of_Siberia_Yagyu_(TV)",

    #-----------KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK----------------#
    "Kage_Jitsuryokusha_2": "Kage_no_Jitsuryokusha_ni_Naritakute!_2nd_Season_(TV)",
    "Kaguya_Ultra_Romantic": "Kaguya-sama_wa_Kokurasetai_-Ultra_Romantic-_(TV)",
    "Kaguya_Tensai_2": "Kaguya-sama_wa_Kokurasetai:_Tensai-tachi_no_Renai_Zunousen_Season_2_(TV)",
    "Kaguya_Ultra_Romantic_2": "Kaguya-sama_wa_Kokurasetai:_Ultra_Romantic_(TV)",
    "Kaguya_Tensai_2nd": "Kaguya-sama_wa_Kokurasetai_:_Tensai-tachi_no_Renai_Zunousen_2nd_Season_(TV)",
    "Kaijuu_Girls_Kuro": "Kaijuu_Girls_Kuro:_Ultra_Kaijuu_Gijinka_Keikaku_(Movie)",
    "Kaijuu_Girls_2": "Kaijuu_Girls:_Ultra_Kaijuu_Gijinka_Keikaku_2nd_Season_(TV)",
    "Kaiko_Ankoku_Heishi": "Kaiko_Sareta_Ankoku_Heishi_(30-dai)_no_Slow_na_Second_Life_(TV)",
    "Kakyuusei_2_Hitomi": "Kakyuusei_2:_Hitomi_no_Naka_no_Shoujo-tachi_(TV)",
    "Kanojo_x3_Sanshimai": "Kanojo_x_Kanojo_x_Kanojo:_Sanshimai_to_no_DokiDoki_Kyoudou_Seikatsu_(OVA)",
    "Kanpeki_Seijo_Ringoku": "Kanpekisugite_Kawaige_ga_Nai_to_Konyakuhakisareta_Seijo_wa_Ringoku_ni_Urareru_(TV)",
    "Katainaka_Kensei": "Katainaka_no_Ossan,_Kensei_ni_Naru:_Tada_no_Inaka_no_Kenjutsu_Shihan_datta_no_ni,_Taiseishita_Deshi-tachi_ga_Ore_wo_Hottekurenai_Ken_(TV)",
    "Katsute_Mahou_Aku": "Katsute_Mahou_Shoujo_to_Aku_wa_Tekitai_shiteita_(TV)",
    "Kawaikereba_Hentai": "Kawaikereba_Hentai_demo_Suki_ni_Natte_Kuremasu_ka_(TV)",
    "Kaze_Shoujo_Jeanie": "Kaze_no_Naka_no_Shoujo:_Kinpatsu_no_Jeanie_(TV)",
    "Keikenzumi_Keiken_Zero": "Keikenzumi_na_Kimi_to,_Keiken_Zero_na_Ore_ga,_Otsukiai_suru_Hanashi_(TV)",
    "Keishicho_Tokunana": "Keishicho_Tokumu-bu_Tokushu_Kyoaku-han_Taisaku-Shitsu_Dai-Nana-ka:_Tokunana_(TV)",
    "100_Kanojo": "Kimi_no_Koto_ga_Daidaidaidaidaisuki_na_100-nin_no_Kanojo_(TV)",
    "100_Kanojo_2": "Kimi_no_Koto_ga_Daidaidaidaidaisuki_na_100-nin_no_Kanojo_2nd_Season_(TV)",
    "Kimi_Boku_Seisen": "Kimi_to_Boku_no_Saigo_no_Senjou,_Aruiwa_Sekai_ga_Hajimaru_Seisen_(TV)",
    "Kimi_Boku_Seisen_2": "Kimi_to_Boku_no_Saigo_no_Senjou,_Aruiwa_Sekai_ga_Hajimaru_Seisen_Season_II_(TV)",
    "Saint_Seiya_Sanctuary": "Knights_of_the_Zodiac:_Saint_Seiya_-_Battle_for_Sanctuary_(TV)",
    "Kindaichi_Kuromajutsu": "Kindaichi_Shounen_no_Jikenbo:_Kuromajutsu_Satsujin_Jiken-hen_(OVA)",
    "Kino_Life_Goes_On": "Kino_no_Tabi:_In_Order_to_Do_Something_-Life_Goes_On-_(Movie)",
    "Kino_Beautiful_World": "Kino_no_Tabi:_The_Beautiful_World_-_The_Animated_Series_(TV)",
    "Kinsou_Vermeil": "Kinsou_no_Vermeil_~Gakeppuchi_Majutsushi_wa_Saikyou_no_Yakusai_to_Mahou_Sekai_wo_Tsukisusumu~_(TV)",
    "Angelique_Kokoro": "Koi_suru_Tenshi_Angelique_~_Kokoro_no_Mezameru_Toki_(TV)",
    "Angelique_Kagayaki": "Koi_Suru_Tenshi_Angelique_~Kagayaki_no_Ashita~_(TV)",
    "Koichoco": "Koi_to_Senkyo_to_Chocolate_(Koichoco,_Love,_Election___Chocolate)_(TV)",
    "NakaImo": "Kono_Naka_ni_Hitori,_Imouto_ga_Iru!_(NakaImo)_(TV)",
    "Yuusha_TUEEE": "Kono_Yuusha_ga_Ore_TUEEE_Kuse_ni_Shinchou_Sugiru_(TV)",
    "Konyaku_Haki_Reijou": "Konyaku_Haki_sareta_Reijou_wo_Hirotta_Ore_ga,_Ikenai_Koto_wo_Oshiekom_(TV)",
    "Koori_Zokusei_Cool": "Koori_Zokusei_Danshi_to_Cool_na_Douryou_Joshi_(TV)",
    "Kosuke_Rikimaru_Ryuu": "Kosuke-sama_Rikimaru-sama:_Konpeitou_no_Ryuu_(OVA)",
    "Kubikiri_Aoiro": "Kubikiri_Cycle:_Aoiro_Savant_to_Zaregototsukai_(OVA)",
    "Kuroiwa_Medaka": "Kuroiwa_Medaka_ni_Watashi_no_Kawaii_ga_Tsuujinai_(TV)",
    "Kyou_Kara_Maou_1_2": "Kyou_Kara_Maou!_1st___2nd_Season_(TV)_(TV)",
    "Kyuukyoku_Full_Dive": "Kyuukyoku_Shinka_shita_Full_Dive_RPG_ga_Genjitsu_yori_mo_Kusoge_Dattara_(TV)",

    #-----------LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL----------------#
    "La_Corda_Secondo": "La_Corda_DOro_~Secondo_Passo~_(TV)",
    "Last_Period_Rasen": "Last_Period:_Owarinaki_Rasen_no_Monogatari_(TV)",
    "Layton_Katri_File": "Layton_Mystery_Tanteisha:_Katri_no_Nazotoki_File_(TV)",
    "LotGH_New_Thesis": "Legend_of_the_Galactic_Heroes_-_The_New_Thesis_-_Encounter_(TV)",
    "Fist_North_Star_Dark": "Legends_of_the_Dark_King_-_A_Fist_of_the_North_Star_Story_(TV)",
    "Lime_iro_Senkitan": "Lime-iro_Senkitan:_The_South_Island_Dream_Romantic_Adventure_(OVA)",
    "Loop_7_Akuyaku_Reijou": "Loop_7-kaime_no_Akuyaku_Reijou_wa,_Moto_Tekikoku_de_Jiyuu_Kimama_na_Hanayome_Seikatsu_wo_Mankitsu_suru_(TV)",
    "El_Melloi_Rail_Zeppelin": "Lord_El-Melloi_II_Sei_no_Jikenbo:_Rail_Zeppelin_Grace_Note_(TV)",
    "Love_Live_Nijigasaki": "Love_Live!_Nijigasaki_Gakuen_School_Idol_Doukoukai_(TV)",
    "Love_Live_Nijigasaki_2": "Love_Live!_Nijigasaki_Gakuen_School_Idol_Doukoukai_2nd_Season_(TV)",
    "Lv2_Cheat_Motoyuusha": "Lv2_kara_Cheat_datta_Motoyuusha_Kouho_no_Mattari_Isekai_Life_(TV)",

    #-----------MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM----------------#
    "Mahouka_Reminiscence": "Mahouka_Koukou_no_Rettousei:_Reminiscence_Arc_(Special)",
    "Mahoutsukai_Narenakatta": "Mahoutsukai_ni_Narenakatta_Onnanoko_no_Hanashi_(TV)",
    "Maji_Otaku_Ribbon": "Maji_de_Otaku_na_English!_Ribbon-chan:_Eigo_de_Tatakau_Mahou_Shoujo_(TV)",
    "Maji_Otaku_Ribbon_TV": "Maji_de_Otaku_na_English!_Ribbon-chan:_Eigo_de_Tatakau_Mahou_Shoujo_-_The_TV_(TV)",
    "Majokko_Alien_X": "Majokko_Club_Yoningumi:_A_Kuukan_kara_no_Alien_X_(OVA)",
    "Maou_Gakuin_Futekigousha": "Maou_Gakuin_no_Futekigousha:_Shijou_Saikyou_no_Maou_no_Shiso,_Tensei_shite_Shison-tachi_no_Gakkou_e_(TV)",
    "Maou_Dorei_Elf": "Maou_no_Ore_ga_Dorei_Elf_wo_Yome_ni_Shitanda_ga,_Dou_Medereba_Ii_(TV)",
    "Maougun_Majutsushi": "Maougun_Saikyou_no_Majutsushi_wa_Ningen_datta_(TV)",
    "Maeterlinck_Aoi_Tori": "Maeterlinck_no_Aoi_Tori:_Tyltyl_Mytyl_no_Bouken_Ryokou_(TV)",
    "Magia_Record_Madoka": "Magia_Record:_Mahou_Shoujo_Madoka___Magica_Gaiden_(TV)",
    "Magia_Record_Madoka_2": "Magia_Record:_Mahou_Shoujo_Madoka___Magica_Gaiden_(TV)_2nd_Season_(TV)",
    "Magia_Record_Final": "Magia_Record:_Mahou_Shoujo_Madoka___Magica_Gaiden_Final_Season_-_Asaki_Yume_no_Akatsuki_(TV)",
    "Negima_Hitotsu_Sekai": "Mahou_Sensei_Negima!_~Mou_Hitotsu_no_Sekai~__(OVA)",
    "Negima_Ala_Alba": "Mahou_Sensei_Negima!_~Shiroki_Tsubasa_Ala_Alba~_(OVA)",
    "Mahou_Shoujo_Nante_2": "Mahou_Shoujo_Nante_Mou_Ii_Desukara._2nd_Season_(TV)",
    "Mahou_Tsukai_Natsu": "Mahou_Tsukai_ni_Taisetsu_na_Koto:_Natsu_no_Sora__(TV)",
    "Mashin_Eiyuuden_Wataru": "Mashin_Eiyuuden_Wataru:_Owarinaki_Toki_no_Monogatari_(OVA)",
    "MASHLE_Kami_Shinkakusha": "MASHLE_Kami_Shinkakusha_Kouho_Senbatsu_Shiken-hen_(TV)",
    "Meitou_Isekai_Onsen": "Meitou_Isekai_no_Yu_Kaitakuki:_Around_40_Onsen_Mania_no_Tensei_Saki_wa,_Nonbiri_Onsen_Tengoku_deshita_(TV)",
    "Gundam_G40": "Mobile_Suit_Gundam_40th_Anniversary_G40_Project_Special_Movie_(ONA)",
    "Gundam_Origin_Suisei": "Mobile_Suit_Gundam:_The_Origin_-_Zenya_Akai_Suisei_(TV)",
    "Gundam_Suisei_2": "Mobile_Suit_Gundam:_Suisei_no_Majo_Season_2_(TV)",
    "Gundam_Origin_Suisei_2": "Mobile_Suit_Gundam:_The_Origin_-_Zenya_Akai_Suisei_(TV)",
    "Mondaiji_Isekai": "Mondaiji-tachi_ga_Isekai_kara_Kuru_Sou_Desu_yo_(TV)",
    "Monster_Strike_Movie": "Monster_Strike_The_Movie:_Hajimari_no_Basho_e_(Movie)",
    "Monster_Strike_Pandora": "Monster_Strike:_Zoku_Saishuu-banashi_-_Pandora_no_Hako_(ONA)",
    "Mori_Youki_Kobito": "Mori_no_Youki_na_Kobito-tachi:_Belfy_to_Lillibit_(TV)",
    "Muhyo_Rouji_Jimusho": "Muhyo_to_Rouji_no_Mahouritsu_Soudan_Jimusho_(TV)",
    "Muhyo_Rouji_Jimusho_2": "Muhyo_to_Rouji_no_Mahouritsu_Soudan_Jimusho_2nd_Season_(TV)",
    "Munto_Tatakai": "Munto:Tenjou-jin_to_Akuto-jin_Saigo_no_Tatakai_(Movie)",
    "Mushoku_Tensei_2": "Mushoku_Tensei_II:_Isekai_Ittara_Honki_Dasu_(TV)",
    "Mushoku_Tensei_2_2": "Mushoku_Tensei_II:_Isekai_Ittara_Honki_Dasu_Part_2_(TV)",
    "Gundam_IGLOO_Apocalypse": "Mobile_Suit_Gundam_MS_IGLOO:_Apocalypse_0079_(OVA)",
    "Gundam_IGLOO_Hidden": "Mobile_Suit_Gundam_MS_IGLOO:_The_Hidden_One_Year_War_(OVA)",
    "Gundam_Seed_Stargazer": "Mobile_Suit_Gundam_Seed_C.E.73:_Stargazer_(ONA)",
    "Gundam_IBO_2": "Mobile_Suit_Gundam:_Iron-Blooded_Orphans_2nd_Season_(TV)",
    "Gundam_IGLOO_Juryoku": "Mobile_Suit_Gundam_MS_IGLOO_2:_Juryoku_Sensen__(OVA)",
    "Merc_Storia_Mukiryoku": "Merc_Storia:_Mukiryoku_no_Shounen_to_Bin_no_Naka_no_Shoujo_(TV)",
    "Mushoku_Tensei_2nd": "Mushoku_Tensei:_Isekai_Ittara_Honki_Dasu_2nd_Season_(TV)",
    "Mental_Choices_Comedy": "My_mental_choices_are_completely_interfering_with_my_school_romantic_comedy_(TV)",

    #-----------NNNNNNNNNNNNNNNNNNNNNNNNN----------------#
    "Naikaku_Kenryoku_Zaizen": "Naikaku_Kenryoku_Hanzai_Kyousei_Torishimarikan_Zaizen_Joutarou_(TV)",
    "Nanatsu_Yonkishi": "Nanatsu_no_Taizai:_Mokushiroku_no_Yonkishi_(TV)",
    "Nanatsu_Fukkatsu": "Nanatsu_no_Taizai:_Imashime_no_Fukkatsu_(TV)",
    "Nanatsu_Yonkishi_2": "Nanatsu_no_Taizai:_Mokushiroku_no_Yonkishi_2nd_Season_(TV)",
    "Nanatsu_Holy_War": "Nanatsu_no_Taizai:_Signs_of_Holy_War_(TV)",
    "Narutaru_Mukuro": "Narutaru:_Mukuro_Naru_Hoshi_Tama_Taru_Ko_(TV)",
    "Rock_Lee_Ninden": "Naruto_SD:_Rock_Lee_no_Seishun_Full-Power_Ninden_(TV)",
    "Rock_Lee_Ninden_2": "Naruto_SD:_Rock_Lee_no_Seishun_Full-Power_Ninden_Mou_Iccho_(TV)",
    "Naruto_Konoha_Gakuen": "Naruto_Shippuden_Omake--Shippu!_Konoha_Gakuen_Den!_(Special)",
    "Naruto_Sage_vs_Sasuke": "Naruto_Shippuden_OVA_Sage_Naruto_vs_Sasuke_(OVA)",
    "Naruto_Road_to_Ninja": "Naruto_Shippuden_Movie_6_-_Road_to_Ninja_(Movie)",
    "Naruto_Storm_Generations": "Naruto_Shippuden_Storm_Generations_OVA_(Special)",
    "Naruto_Sunny_Side": "Naruto_Shippuden:_Sunny_Side_Battle_(Special)",
    "Naruto_Lost_Towers": "Naruto_Shippuuden_Movie_4_-_The_Lost_Towers_(Movie)",
    "Naruto_Rosuto_Taw": "Naruto_Shippuuden_Movie_4:_Za_Rosuto_Taw___(Movie)",
    "Naruto_Hi_no_Ishi": "Naruto_Shippuuden:_Hi_no_Ishi_o_Tsugumono_(Movie)",
    "Naruto_Gelel": "Naruto_the_Movie_Legend_of_the_Stone_of_Gelel_(Movie)",
    "Naruto_Snow": "Naruto_the_Movie_Ninja_Clash_in_the_Land_of_Snow_(Movie)",
    "Naruto_Crescent_Moon": "Naruto_the_Movie:_Guardians_of_the_Crescent_Moon_Kingdom_(Movie)",
    "Naruto_Takigakure": "Naruto:_Takigakure_no_Shitou_-_Ore_ga_Eiyuu_Dattebayo!_(Special)",
    "Naruto_Jounin_vs_Genin": "Naruto:_Finally_a_Clash!!_Jounin_vs._Genin!_(OVA)",
    "Nasu_Migratory_Bird": "Nasu:_A_Migratory_Bird_with_Suitcase_(OVA)",
    "Nausica_Valley": "Nausica___of_the_Valley_of_the_Wind_(Movie)",
    "Naze_Boku_Sekai": "Naze_Boku_no_Sekai_wo_Daremo_Oboeteinai_no_ka_(TV)",
    "NEET_Kunoichi": "NEET_Kunoichi_to_Naze_ka_Dousei_Hajimemashita_(TV)",
    "Nejimaki_Alderamin": "Nejimaki_Seirei_Senki:_Tenkyou_no_Alderamin_(TV)",
    "Nekojiru_Jirujiru": "Nekojiru_Gekijou_Jirujiru_Original_(TV)",
    "Neo_Angelique_Abyss": "Neo_Angelique_Abyss:_Second_Age_(TV)",
    "Netoge_Yome": "Netoge_no_Yome_wa_Onnanoko_ja_Nai_to_Omotta_(TV)",
    "Dream_Hunter_Rem": "New_Dream_Hunter_Rem:_Yume_no_Kishitachi_(OVA)",
    "Night_Warriors_Darkstalkers": "Night_Warriors_-_Darkstalkers_Revenge_(OVA)",
    "Nil_Admirari_Tenbin": "Nil_Admirari_no_Tenbin:_Teito_Genwaku_Kitan_(TV)",
    "Ningen_Fushin_Boukensha": "Ningen_Fushin_no_Boukensha-tachi_ga_Sekai_wo_Sukuu_You_Desu_(TV)",
    "Ninja_Koroshiya_Ninkoro": "Ninja_to_Koroshiya_no_Futarigurashi,_Ninkoro_(TV)",
    "Nintama_Ninjutsu_Gakuen": "Nintama_Rantarou_Movie:_Ninjutsu_Gakuen_Zenin_Shutsudou!_no_Dan_(Movie)",
    "Noblesse_Destruction": "Noblesse_-_The_Beginning_of_Destruction_(OVA)",
    "Nobunaga_Shinobi_Anegawa": "Nobunaga_no_Shinobi:_Anegawa_Ishiyama-hen_(TV)",
    "Nobunaga_Shinobi_Ise": "Nobunaga_no_Shinobi:_Ise_Kanegasaki-hen_(TV)",
    "Nurse_Witch_Komugi_Return": "Nurse_Witch_Komugi_-_Return_to_Subject_Special_(Special)",
    "Nurse_Witch_Komugi_Z": "Nurse_Witch_Komugi-chan_Magikarte_Z_(OVA)",

    "Okinawa_Hougen_Tsurai": "Okinawa_de_Suki_ni_Natta_Ko_ga_Hougen_Sugite_Tsura_Sugiru_(TV)",
    "Omiai_Oshiego_Mondaiji": "Omiai_Aite_wa_Oshiego,_Tsuyokina,_Mondaiji_(TV)",
    "OP_Movie_3_Chopper": "One_Piece_Movie_3_-_Chopper_and_the_Kingdom_of_Strange_Animals_(Movie)",
    "OP_Movie_6_Omatsuri": "One_Piece_Movie_6_-_Baron_Omatsuri_and_the_Secret_Island_(Movie)",
    "OP_Movie_8_Arabasta": "One_Piece_Movie_8_-_Episode_of_Arabasta_-_The_Desert_Princess_and_the_Pirates_(Movie)",
    "OP_Movie_9_Chopper_Plus": "One_Piece_Movie_9_-_Episode_of_Chopper_Plus_-_Bloom_in_the_Winter,_Miracle_Cherry_Blossom_(Movie)",
    "Onii-chan_Zenzen_Suki": "Onii-chan_no_Koto_nanka_Zenzen_Suki_Janain_Dakara_ne!!_(TV)",
    "OniAi": "Onii-chan_Dakedo_Ai_Sae_Areba_Kankeinai_yo_ne!_(OniAi)_(TV)",
    "Ookami_Koushinryou_Wolf": "Ookami_to_Koushinryou:_Merchant_Meets_the_Wise_Wolf_(TV)",
    "Ore_Level_Up_2": "Ore_dake_Level_Up_na_Ken_Season_2:_Arise_from_the_Shadow_(TV)",
    "Ore_Imouto_dakedo": "Ore_ga_Suki_nano_wa_Imouto_dakedo_Imouto_ja_Nai_(TV)",
    "Oreimo": "Ore_no_Imouto_ga_Konna_ni_Kawaii_Wake_ga_Nai_(TV)",
    "Oreimo_2": "Ore_no_Imouto_ga_Konna_ni_Kawaii_Wake_ga_Nai_2_(TV)",
    "OreShura": "Ore_no_Kanojo_to_Osananajimi_ga_Shuraba_Sugiru_(OreShura)_(TV)",
    "Ore_no_Nai_Sentakushi": "Ore_no_N__nai_Sentakushi_ga,_Gakuen_Love_Come_o_Zenryoku_de_Jama_Shiteiru_(TV)",
    "Ore_Yubi_Midarero": "Ore_no_Yubi_de_Midarero._Heitengo_Futarikiri_no_Salon_de_(TV)",
    "Ore_Parry_Saikyou": "Ore_wa_Subete_wo_Parry_suru:_Gyaku_Kanchigai_no_Sekai_Saikyou_wa_Boukensha_ni_Naritai_(TV)",
    "Oretachi_Tsubasa_Nai": "Oretachi_ni_Tsubasa_wa_Nai_______under_the_innocent_sky_(TV)",
    "Osananajimi_Makenai": "Osananajimi_ga_Zettai_ni_Makenai_Love_Comedy_(TV)",
    "Rilu_Rilu_Fairilu": "Oshiete_Mahou_no_Pendulum:_Rilu_Rilu_Fairilu_(TV)",
    "Osomatsu_Movie_Tanpen": "Osomatsu-san_Movie:_Gekijou_Koukai_Kinen_-_Original_Tanpen_Gekijou_(ONA)",
    "HameFura": "Otome_Game_no_Hametsu_Flag_shika_Nai_Akuyaku_Reijou_ni_Tensei_shiteshimatta_(TV)",
    "HameFura_X": "Otome_Game_no_Hametsu_Flag_shika_Nai_Akuyaku_Reijou_ni_Tensei_shiteshimatta..._X_(TV)",
    "Otome_Game_Mob": "Otome_Game_Sekai_wa_Mob_ni_Kibishii_Sekai_desu_(TV)",
    "Otonari_Tenshi": "Otonari_no_Tenshi-sama_ni_Itsunomanika_Dame_Ningen_ni_Sareteita_Ken_(TV)",
    "Ouran_Live_JDrama": "Ouran_High_School_Host_Club_Live-Action_JDrama_(TV)",
    "Ouran_Live_Movie": "Ouran_High_School_Host_Club_Live-Action_Movie_(Movie)",
    "Overlord_Ple_Ple_Clem": "Overlord:_Ple_Ple_Pleiades_-_Clementine_the_Fugitive_(ONA)",

    "Party_Tsuihou_Saikyou": "Party_kara_Tsuihou_sareta_Sono_Chiyushi,_Jitsu_wa_Saikyou_ni_Tsuki_(TV)",
    "Pokemon_12_Arceus": "Pokemon_12th_Movie_Arceus_and_Jewel_Of_Liife_(Movie)",
    "Pokemon_8_Lucario_Mew": "Pokemon_Movie_08_-_Lucario_and_the_Mystery_of_Mew_(Movie)",
    "Pokemon_9_Ranger": "Pokemon_Movie_09_-_Pok__mon_Ranger_and_the_Temple_of_the_Sea_(Movie)",
    "Pokemon_11_Giratina": "Pokemon_Movie_11_-_Giratina_and_the_Sky_Warrior_(Movie)",
    "Pokemon_13_Zoroark": "Pokemon_Movie_13_-_Zoroark:_Master_of_Illusions_(Movie)",
    "Pokemon_15_Kyurem": "Pokemon_Movie_15_-_Kyurem_vs._The_Sword_of_Justice_(Movie)",
    "Pokemon_16_Genesect": "Pokemon_Movie_16_-_Genesect_and_The_Legend_Awaken_(Movie)",
    "Pokemon_17_Diancie": "Pokemon_Movie_17:_Hakai_no_Mayu_to_Diancie_(Movie)",
    "Pokemon_19_Volcanion": "Pokemon_Movie_19:_Volcanion_to_Karakuri_no_Magearna_(Movie)",
    "Pokemon_22_Mewtwo": "Pokemon_Movie_22:_Mewtwo_no_Gyakushuu_Evolution_(Movie)",
    "Pokemon_Black_Victini": "Pok__mon_the_Movie:_Black_-_Victini_and_Reshiram_(Movie)",
    "Pokemon_White_Victini": "Pok__mon_the_Movie:_White_-_Victini_and_Zekrom_(Movie)",
    "Precure_All_Stars_Mirai": "Precure_All_Stars_New_Stage:_Mirai_no_Tomodachi_(Movie)",
    "PoT_Another_Story": "Prince_of_Tennis:_Another_Story_~Messages_From_Past_and_Future~_(OVA)",
    "Prism_Magical_Generations": "Prism_Magical_____PRISM_Generations!_(OVA)",
    "Layton_Eternal_Diva": "Professor_Layton_and_the_Eternal_Diva_(Movie)",
    "Puss_in_Boots_3": "Puss_in_Boots_3_-_Travels_Around_the_World_in_80_Days_(Movie)",

    "Quiz_Magic_Academy_OVA": "Quiz_Magic_Academy_~The_Original_Animation~_(OVA)",

    "ReZero_2": "Re:Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season_(TV)",
    "ReZero_2_Part2": "Re:Zero_kara_Hajimeru_Isekai_Seikatsu_2nd_Season_Part_2_(TV)",
    "ReZero_3": "Re:Zero_kara_Hajimeru_Isekai_Seikatsu_3rd_Season_(TV)",
    "ReZero_Shin_Henshuu": "Re:ZERO_kara_Hajimeru_Isekai_Seikatsu:_Shin_Henshuu-ban_(TV)",
    "Luminous_Witches": "Renmei_Kuugun_Koukuu_Mahou_Ongakutai_Luminous_Witches_(TV)",
    "RikeKoi_Heart": "Rikei_ga_Koi_ni_Ochita_no_de_Shoumei_shitemita._Heart_(TV)",
    "Rinne_Lagrange_Flower": "Rinne_no_Lagrange:_Flower_declaration_of_your_heart_(TV)",
    "Rokka_Yuusha": "Rokka_no_Yuusha:_Braves_of_the_Six_Flowers_(TV)",
    "Rokudenashi_Akashic": "Rokudenashi_Majutsu_Koushi_to_Akashic_Records_(TV)",
    "Rougo_Kinka": "Rougo_ni_Sonaete_Isekai_de_8-manmai_no_Kinka_wo_Tamemasu_(TV)",
    "Rurouni_Requiem": "Rur__ni_Kenshin_____Meiji_Kenkaku_Romantan_____Ishin_Shishi_e_no_Requiem_(TV)",
    "Rurouni_Kyoto": "Rurouni_Kenshin:_Meiji_Kenkaku_Romantan_-_Kyoto_Douran_(TV)",
    "Rurouni_2023": "Rurouni_Kenshin_-Meiji_Kenkaku_Romantan-_(2023)_(TV)",
    "Ryza_Atelier_Tokoyami": "Ryza_no_Atelier:_Tokoyami_no_Joou_to_Himitsu_no_Kakurega_(TV)",
    "Nanana_Maizoukin": "Ry__gaj___Nanana_no_Maiz__kin_(TV)",

    "Behemoth_Neko_Elf_Pet": "S-Rank_Monster_no_Behemoth_Dakedo,_Neko_to_Machigawarete_Elf_Musume_no_Pet_Toshite_Kurashitemasu_(TV)",
    "Saezuru_Clouds_Gather": "Saezuru_Tori_wa_Habatakanai:_The_Clouds_Gather_(Movie)",
    "Saijaku_Tamer_Gomi_Hiroi": "Saijaku_Tamer_wa_Gomi_Hiroi_no_Tabi_wo_Hajimemashita_(TV)",
    "Saihate_Paladin_Tetsusabi": "Saihate_no_Paladin:_Tetsusabi_no_Yama_no_Ou_(TV)",
    "Imouto_Yousu_Okashiinda": "Saikin,_Imouto_no_Yousu_ga_Chotto_Okashiinda_ga._(TV)",
    "Saikyou_Ousama_Nidome": "Saikyou_no_Ousama,_Nidome_no_Jinsei_wa_Nani_wo_Suru_(TV)",
    "Saikyou_Wajutsushi_Clan": "Saikyou_no_Shienshoku_Wajutsushi_de_Aru_Ore_wa_Sekai_Saikyou_Clan_wo_Shitagaeru_(TV)",
    "Saikyou_Tank_Meikyuu": "Saikyou_Tank_no_Meikyuu_Kouryaku:_Tairyoku_9999_no_Rare_Skill-mochi_Tank,_Yuusha_Party_wo_Tsuihou_sareru_(TV)",
    "Saint_Seiya_Sanctuary_2": "Saint_Seiya:_Knights_of_the_Zodiac_-_Battle_for_Sanctuary_Part_2_(TV)",
    "Saint_Seiya_Elysion": "Saint_Seiya:_The_Hades_Chapter_-_Elysion_(OVA)",
    "Saint_Seiya_Inferno": "Saint_Seiya:_The_Hades_Chapter_-_Inferno_(OVA)",
    "Saint_Seiya_Sanctuary_OVA": "Saint_Seiya:_The_Hades_Chapter_-_Sanctuary_(OVA)",
    "Sakura_Chikai_Yell": "Sakura_no_Chikai:_Marronni_Yell_-_Higashi_no_Hichou_Shimotsuke-shi_wo_Yell!_(TV)",
    "Sakura_Taisen_Sumire": "Sakura_Taisen_Sumire_Kanzaki_Intai_Kinen:_Su_Mi_Re_(OVA)",
    "Sakurako_Shitai_Umatteiru": "Sakurako-san_no_Ashimoto_ni_wa_Shitai_ga_Umatteiru_(TV)",
    "Salaryman_Shitennou": "Salaryman_ga_Isekai_ni_Ittara_Shitennou_ni_Natta_Hanashi_(TV)",
    "Ginga_Tetsudou_Andromeda": "Sayonara_Ginga_Tetsudou_999:_Andromeda_Shuuchakueki_(Movie)",
    "Scramble_Wars_Genom": "Scramble_Wars:_Tsuppashire!_Genom_Trophy_Rally_(OVA)",
    "Secret_Mission_Sennyuu": "Secret_Mission:_Sennyuu_Sousakan_wa_Zettai_ni_Makenai!_(TV)",
    "SD_Gundam_Sangokuden": "SD_Gundam_Sangokuden_Brave_Battle_Warriors_(TV)",
    "Seija_Musou_Salaryman": "Seija_Musou:_Salaryman,_Isekai_de_Ikinokoru_Tame_ni_Ayumu_Michi_(TV)",
    "Seiken_Densetsu_Teardrop": "Seiken_Densetsu:_Legend_of_Mana_-The_Teardrop_Crystal_(TV)",
    "Seijo_Maryoku_2": "Seijo_no_Maryoku_wa_Bannou_Desu_Season_2_(TV)",
    "Seikima_Humane_Society": "Seikima_II_Humane_Society:_Jinrui_Ai_ni_Michita_Shakai_(OVA)",
    "Bunny_Girl_Senpai": "Seishun_Buta_Yarou_wa_Bunny_Girl_Senpai_no_Yume_wo_Minai_(TV)",
    "Seitokai_Ichizon_Hekiyoh": "Seitokai_no_Ichizon_-_Hekiyoh_Gakuen_Seitokai_Gijiroku_(TV)",
    "Sekai_Saikou_Ansatsusha": "Sekai_Saikou_no_Ansatsusha,_Isekai_Kizoku_ni_Tensei_suru_(TV)",
    "Sengoku_Majin_Etranger": "Sengoku_Majin_Goushougun:_Toki_no_Etranger_(Movie)",
    "Senran_Kagura_Tokyo": "Senran_Kagura_Shinovi_Master:_Tokyo_Youma-hen_(TV)",
    "Seven_Knights_Revolution": "Seven_Knights_Revolution:_Eiyuu_no_Keishousha_(TV)",
    "Daimaou_Murabito_A": "Shijou_Saikyou_no_Daimaou,_Murabito_A_ni_Tensei_suru_(TV)",
    "SHIMONETA": "SHIMONETA:_A_Boring_World_Where_the_Concept_of_Dirty_Jokes_Doesn___t_Exist_(TV)",
    "Shin_Nakama_Slow_Life": "Shin_no_Nakama_ja_Nai_to_Yuusha_no_Party_wo_Oidasareta_node,_Henkyou_de_Slow_Life_suru_Koto_ni_Shimashita_(TV)",
    "Shin_Nakama_Slow_Life_2": "Shin_no_Nakama_ja_Nai_to_Yuusha_no_Party_wo_Oidasareta_node,_Henkyou_de_Slow_Life_suru_Koto_ni_Shimashita_2nd_(TV)",
    "Shin_Shinka_no_Mi": "Shin_Shinka_no_Mi:_Shiranai_Uchi_ni_Kachigumi_Jinsei_(TV)",
    "Shingeki_Final_Chapters": "Shingeki_no_Kyojin:_The_Final_Season_-_The_Final_Chapters_(TV)",
    "Shinka_no_Mi": "Shinka_no_Mi:_Shiranai_Uchi_ni_Kachigumi_Jinsei_(TV)",
    "Shinkalion": "Shinkansen_Henkei_Robo_Shinkalion_the_Animation_(TV)",
    "Shinkalion_Z": "Shinkansen_Henkei_Robo_Shinkalion_Z_the_Animation_(TV)",
    "Shinmai_Ossan_Muteki": "Shinmai_Ossan_Boukensha,_Saikyou_Party_ni_Shinu_hodo_Kitaerarete_Muteki_ni_Naru_(TV)",
    "Shirobuta_Kizoku": "Shirobuta_Kizoku_desu_ga_Zense_no_Kioku_ga_Haeta_node_Hiyoko_na_Otouto_Sodatemasu_(TV)",
    "Shokugeki_Toutsuki": "Shokugeki_no_Souma:_San_no_Sara_-_Toutsuki_Ressha-hen_(TV)",
    "Rakugo_Sukeroku": "Shouwa_Genroku_Rakugo_Shinjuu:_Sukeroku_Futatabi-hen_(TV)",
    "Shuumatsu_Sukutte": "Shuumatsu_Nani_Shitemasu_ka__Isogashii_desu_ka__Sukutte_Moratte_Ii_desu_ka__(TV)",
    "Slime_300_Max": "Slime_Taoshite_300-nen,_Shiranai_Uchi_ni_Level_Max_ni_Nattemashita_(TV)",
    "Slime_300_Max_2": "Slime_Taoshite_300-nen,_Shiranai_Uchi_ni_Level_Max_ni_Nattemashita_2nd_Season_(TV)",
    "Slime_300_Max_2nd": "Slime_Taoshite_300-nen,_Shiranai_Uchi_ni_Level_Max_ni_Nattemashita:_2nd_Season_(TV)",
    "Sokushi_Cheat_Saikyou": "Sokushi_Cheat_ga_Saikyou_Sugite,_Isekai_no_Yatsura_ga_Marude_Aite_ni_(TV)",
    "Hanabira_Kuchizuke": "sono_hanabira_ni_kuchizuke_o_-_anata_to_koibito_tsunagi_(OVA)",
    "Sora_Miageru_Shoujo": "Sora_wo_Miageru_Shoujo_no_Hitomi_ni_Utsuru_Sekai_(TV)",
    "Anpanman_Nakama": "Sore_Ike!_Anpanman:_Anpanman_to_Yukai_na_Nakama-tachi_(Movie)",
    "Anpanman_Grand_Prix": "Sore_Ike!_Anpanman:_Hashire!_Wakuwaku_Anpanman_Grand_Prix_(Movie)",
    "Anpanman_Naganegiman": "Sore_Ike!_Anpanman:_Kaiketsu_Naganegiman_to_Yakisobapanman_(Movie)",
    "Anpanman_Laura": "Sore_Ike!_Anpanman:_Roll_to_Laura_Ukigumojou_no_Himitsu_(Movie)",
    "Anpanman_Maki_chan": "Sore_Ike!_Anpanman:_Tekka_no_Maki-chan_to_Kin_no_Kamameshidon_(Movie)",
    "Uchuu_Senkan_Yohko": "Soreyuke!_Uchuu_Senkan_Yamamoto_Yohko_(1999)_(TV)",
    "Votoms_Red_Shoulder": "Soukou_Kihei_Votoms:_Red_Shoulder_Document_-_Yabou_no_Roots_(OVA)",
    "Fafner_Exodus": "Soukyuu_no_Fafner:_Dead_Aggressor_-_Exodus_(TV)",
    "Steins_Gate_Divide_Zero": "Steins_Gate:_Kyoukaimenjou_no_Missing_Link_-_Divide_By_Zero_(OVA)",
    "Stella_C3": "Stella_Womens_Academy,_High_School_Division_Class_C3_(TV)",
    "Suki_Naru_Kokuhaku": "Suki_ni_Naru_Sono_Shunkan_wo:_Kokuhaku_Jikkou_Iinkai_(Movie)",
    "Cosmos_Dokkoida": "Sumeba_Miyako_no_Cosmos-sou_Suttoko_Taisen_Dokkoida_(TV)",
    "SRW_OG_Animation": "Super_Robot_Wars_Original_Generation_-_The_Animation_(OAV)_(OVA)",
    "Samy_Missing_99": "Superdimensional_Romanesque_Samy_-_Missing_99_(OVA)",
    "SAO_GGO": "Sword_Art_Online_Alternative:_Gun_Gale_Online_(TV)",
    "SAO_GGO_2": "Sword_Art_Online_Alternative:_Gun_Gale_Online_II_(TV)",
    "SAO_Ordinal_Scale": "Sword_Art_Online_the_Movie:_Ordinal_Scale_(Movie)",
    "SAO_War_Underworld": "Sword_Art_Online:_Alicization_-_War_of_Underworld_(TV)",

    "Taishou_Itsuwari_Bridal": "Taishou_Itsuwari_Bridal:_Migawari_Hanayome_to_Gunpuku_no_Mouai_(TV)",
    "Tales_Crestoria_Toga": "Tales_of_Crestoria:_Toga_Waga_wo_Shoite_Kare_wa_Tatsu_(Special)",
    "Tales_Symphonia_Tougou": "Tales_of_Symphonia_The_Animation:_Sekai_Tougou-hen_(OVA)",
    "Last_Dungeon_Shounen": "Tatoeba_Last_Dungeon_Mae_no_Mura_no_Shounen_ga_Joban_no_Machi_de_Kurasu_Youna_Monogatari_(TV)",
    "Tearmoon_Teikoku": "Tearmoon_Teikoku_Monogatari:_Dantoudai_kara_Hajimaru,_Hime_no_Tensei_Gyakuten_Story_(TV)",
    "Tenchi_Mihoshi": "Tenchi_Muyou!:_Galaxy_Police_Mihoshi_Space_Adventure_(OVA)",
    "Tensei_Kenja_Isekai": "Tensei_Kenja_no_Isekai_Life_~Dai-2_no_Shokugyou_wo_Ete,_Sekai_Saikyou_ni_Narimashita~_(TV)",
    "Tensei_Kizoku_Boukenroku": "Tensei_Kizoku_no_Isekai_Boukenroku:_Jichou_wo_Shiranai_Kamigami_no_Shito_(TV)",
    "Tensei_Dainana_Ouji": "Tensei_shitara_Dainana_Ouji_Datta_node,_Kimama_ni_Majutsu_wo_Kiwamemasu_(TV)",
    "Tensura_Nikki": "Tensura_Nikki:_Tensei_shitara_Slime_Datta_Ken_(TV)",
    "Tesagure_Sharumu": "Tesagure_Bukatsumono_Spin-off_Purupurun_Sharumu_to_Asobou_(TV)",
    "Tezuka_Kaijiken": "Tezuka_Osamu_ga_Kieta_!_20_Seiki_Saigo_no_Kaijiken_(Special)",
    "Tezuka_Seisho": "Tezuka_Osamu_no_Kyuuyaku_Seisho_Monogatari:_In_the_Beginning_(TV)",
    "Morris_Lessmore": "The_Fantastic_Flying_Books_of_Mr.Morris_Lessmore_(2011)_(Movie)",
    "iDOLM_STER_Movie": "The_iDOLM_STER_Movie:_Kagayaki_no_Mukougawa_e!_(Movie)",
    "Jungle_Guu_Final": "The_Jungle_Was_Always_Nice_The_Came_Guu_Final_(OVA)",
    "Jungle_Guu": "The_Jungle_was_Always_Nice_then_Along_Came_Guu_(TV)",
    "Jungle_Guu_Deluxe": "The_Jungle_was_Always_Nice_then_Along_Came_Guu_Deluxe_(TV)",
    "Sen_no_Kiseki_Northern": "The_Legend_of_Heroes:_Sen_no_Kiseki_-_Northern_War_(TV)",
    "Trails_in_Sky": "The_Legend_of_Heroes:_Trails_in_The_Sky_(Special)",
    "Moon_Tsuki_Hoshii": "The_Moon_-_Tsuki_ga_Hoshii_to___jo-sama_ga_Naita_(Movie)",
    "Fist_North_Star_Revenge": "The_New_Fist_of_the_North_Star:_Kens_Revenge_(OVA)",
    "PoT_Two_Samurais": "The_Prince_of_Tennis:_Two_Samurais,_The_First_Game_(Movie)",
    "PoT_U17_Semifinal": "The_Prince_of_Tennis_II_U-17_World_Cup_Semifinal_(TV)",
    "TWOGK_Kanon": "The_World_Only_God_Know:Magical_Star_Kanon_100__(OVA)",
    "TWOGK_Goddesses": "The_World_Only_God_Knows_III:_Goddesses_Arc_(TV)",
    "Time_Travel_Shoujo": "Time_Travel_Shoujo:_Mari_Waka_to_8-nin_no_Kagakusha-tachi_(TV)",
    "Index_Endymion": "To_aru_Majutsu_no_Index_-_Endymion_no_Kiseki_(Movie)",
    "Hikuushi_Princess": "Toaru_Hikuushi_e_no_Tsuioku_-_The_Princess_and_the_Pilot_(Movie)",
    "PriPara_Grand_Prix": "Tobidasu_PriPara:_Mi~nna_de_Mezase!_Idol___Grand_Prix_(Movie)",
    "Tokidoki_Alya_san": "Tokidoki_Bosotto_Russia-go_de_Dereru_Tonari_no_Alya-san_(TV)",
    "Touken_Ranbu_Setsugetsuka": "Toku:_Touken_Ranbu_-_Hanamaru_-_Setsugetsuka_(Movie)",
    "Tokyo_Majin_Dai_Ni": "Tokyo_Majin_Gakuen_Kenpuchou_Tou_Dai_Ni_Maku_(TV)",
    "Tomica_Drive_Head": "Tomica_Hyper_Rescue_Drive_Head:_Kidou_Kyuukyuu_Keisatsu_(TV)",
    "Touyama_Sakura_Gold": "Touyama_Sakura_Uchuu_Chou:_Yatsu_no_Na_wa_Gold_(OVA)",
    "Trickster_Ranpo": "Trickster:_Edogawa_Ranpo_Shounen_Tanteidan_Yori_(TV)",
    "Tsubasa_Birdcage": "Tsubasa_RESERVoir_CHRoNiCLE_the_Movie:_The_Princess_in_the_Birdcage_Kingdom_(Movie)",
    "Tsuki_Michibiku_2": "Tsuki_ga_Michibiku_Isekai_Douchuu_2nd_Season_(TV)",
    "Tsundere_Lieselotte": "Tsundere_Akuyaku_Reijou_Lieselotte_to_Jikkyou_no_Endou-kun_to_Kaisetsu_no_Kobayashi-san_(TV)",
    "Tsuujou_Kougeki_Okaasan": "Tsuujou_Kougeki_ga_Zentai_Kougeki_de_Ni-kai_Kougeki_no_Okaasan_wa_Suki_Desu_ka_(TV)",
    

    "UFO_Valkyrie_2": "UFO_Ultramaiden_Valkyrie_2:_December_Nocturne_(TV)",
    "Yamato_2202": "Uchuu_Senkan_Yamato_2202:_Ai_no_Senshi-tachi_(OVA)",
    "Uchiage_Hanabi": "Uchiage_Hanabi,_Shita_kara_Miru_ka__Yoko_kara_Miru_ka__(Movie)",
    "Uchi_no_Ko_Maou": "Uchi_no_Ko_no_Tame_naraba,_Ore_wa_Moshikashitara_Maou_mo_Taoseru_kamo_Shirenai_(TV)",
    "Chiisai_Senpai": "Uchi_no_Kaisha_no_Chiisai_Senpai_no_Hanashi_(TV)",
    "Ultra_Nyan": "Ultra_Nyan:_Hoshizora_kara_Maiorita_Fushigi_Neko_(Movie)",
    "Ultraman_Kids": "Ultraman_Kids:_Haha_wo_Tazunete_3000-man_Kounen_(TV)",
    "Ulysses_Jehanne": "Ulysses:_Jehanne_Darc_to_Renkin_no_Kishi_(TV)",
    "Uma_Musume_Tobira": "Uma_Musume:_Pretty_Derby_-_Shinjidai_no_Tobira_(TV)",
    "Umi_Monogatari": "Umi_Monogatari_~Anata_ga_Ite_Kureta_Koto~_(TV)",
    "Urotsukidoji_2": "Urotsukid__ji_II:_Legend_of_the_Demon_Womb_(OVA)",
    "Urotsukidoji_3": "Urotsukid__ji_III:_Return_of_the_Overfiend_(OVA)",
    "UtaPri_Maji_3000": "Uta_no_Prince-sama_-_Maji_Love_3000__Revolutions_(TV)",
    "UtaPri_RISH_Tours": "Uta_no___Prince-sama____Maji_Love_ST___RISH_Tours_~Tabi_no_Hajimari~_(TV)",

    "Vigilante_Illegals": "Vigilante:_Boku_no_Hero_Academia_Illegals_(TV)",
    "Visionaries_Knight": "Visionaries_Knights_of_the_Magical_Light_(TV)",
    "VTuber_Nanda": "VTuber_Nanda_ga_Haishin_Kiri_Wasuretara_Densetsu_ni_Natteta_(TV)",
    
    "Raeliana_Duke": "Why_Raeliana_Ended_Up_at_the_Dukes_Mansion_(TV)",
    "World_Destruction": "World_Destruction:_Sekai_Bokumetsu_no_Rokunin_(TV)",
    "Watashi_Heikinchi": "Watashi,_Nouryoku_wa_Heikinchi_de_tte_Itta_yo_ne!_(TV)",
    "Coffee_Samurai": "Watashi_no_Coffee_Samurai:_Jihanki-teki_na_Kareshi_(Special)",
    "Watamote": "Watashi_ga_Motenai_no_wa_Dou_Kangaete_mo_Omaera_ga_Warui!_(TV)",

    "Oregairu": "Yahari_Ore_no_Seishun_Love_Come_wa_Machigatteiru_(TV)",
    "Oregairu_Zoku": "Yahari_Ore_no_Seishun_Love_Come_wa_Machigatteiru._Zoku_(TV)",
    "Oregairu_Kan": "Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru._Kan_(TV)",
    "Oregairu_Zoku_2": "Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru._Zoku_(TV)",
    "Yamato_Nadeshiko_JDrama": "Yamato_Nadeshiko_Shichi_Henge_Live-Action_JDrama_(TV)",
    "Yarinaoshi_Reijou": "Yarinaoshi_Reijou_wa_Ryuutei_Heika_wo_Kouryakuchuu_(TV)",
    "Yawaraka_Sangokushi": "Yawaraka_Sangokushi_Tsukisase!!_Ryofuko-chan_(TV)",
    "Yokohama_Kaidashi": "Yokohama_Kaidashi_Kikou:_Quiet_Country_Cafe_(OVA)",
    "Youre_Under_Arrest_2": "Youre_Under_Arrest_2nd_Season_Fast___Furious_(TV)",
    "Youkai_Watch_Jam": "Youkai_Watch_Jam:_Youkai_Gakuen_Y_-_N_to_no_Souguu_(TV)",
    "Youkai_Watch_1": "Youkai_Watch_Movie_1:_Tanjou_no_Himitsu_da_Nyan!_(Movie)",
    "Youkai_Watch_2": "Youkai_Watch_Movie_2:_Enma_Daiou_to_Itsutsu_no_Monogatari_da_Nyan!_(Movie)",
    "Youkai_Watch_3": "Youkai_Watch_Movie_3:_Soratobu_Kujira_to_Double_Sekai_no_Daibouken_da_Nyan!_(Movie)",
    "Youkai_Watch_4": "Youkai_Watch_Movie_4:_Shadow_Side_-_Oni-ou_no_Fukkatsu_(Movie)",
    "Classroom_Elite": "Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_(TV)",
    "Classroom_Elite_2": "Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_2nd_Season_(TV)",
    "Classroom_Elite_3": "Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_3rd_Season_(TV)",
    "5000nen_Dragon": "Yowai_5000-nen_no_Soushoku_Dragon,_Iwarenaki_Jaryuu_Nintei_(TV)",
    "5000nen_Dragon_2": "Yowai_5000-nen_no_Soushoku_Dragon,_Iwarenaki_Jaryuu_Nintei_2nd_Season_(TV)",
    "Ys_Adol_Christine": "Ys:_Tenkuu_no_Shinden_-_Adol_Christine_no_Bouken_(OVA)",
    "YG0_5Ds_Stardust": "Yu-Gi-Oh!_5Ds_-_OVA_-_Evolving_Duel!_Stardust_vs_Red_Demon_(OVA)",
    "Yume_Kakeru_Kougen": "Yume_Kakeru_Kougen:_Kiyosato_no_Chichi_Paul_Rusch_(Movie)",
    "100_Ouji-sama": "Yume_Oukoku_to_Nemureru_100_Nin_no_Ouji-sama_(TV)",
    "100_Ouji-sama_Shorts": "Yume_Oukoku_to_Nemureru_100_Nin_no_Ouji-sama:_Short_Stories_(TV)",
    "Yuusha_Narenakatta": "Y__sha_ni_Narenakatta_Ore_wa_Shibushibu_Sh__shoku_o_Ketsui_Shimashita_(TV)",
    "YuYuYu_Dai_Mankai": "Yuuki_Yuuna_wa_Yuusha_de_Aru:_Dai_Mankai_no_Shou_(TV)",
    "YuYuYu_Washio": "Yuuki_Yuuna_wa_Yuusha_de_Aru:_Washio_Sumi_no_Shou_(TV)",
    "YuYuYu_Yuusha": "Yuuki_Yuuna_wa_Yuusha_de_Aru:_Yuusha_no_Shou_(TV)",

    "xxxHoLic_Midsummer": "xxxHOLiC_The_Movie:_A_Midsummer_Nights_Dream_(Movie)",
    
    "Zetsuen_no_Tempest_Blaster": "Zetsuen_no_Tempest:_The_Civilization_Blaster_(TV)",
    "Zettai_Karen_Children": "Zettai_Karen_Children_OVA:_Aitazousei!_Ubawareta_Mirai__(TV)",
    "Zettai_Karen_Children:_The_Unlimited_Hyoubu_Kyousuke_(TV)": "Zettai_Karen_Children:_The_Unlimited_Hyoubu_Kyousuke_(TV)",
    "Zom_100:_Zombie_ni_Naru_made_ni_Shitai_100_no_Koto_(TV)": "Zom_100:_Zombie_ni_Naru_made_ni_Shitai_100_no_Koto_(TV)",
    "Zutto_Mae_Kara_Suki_Deshita.:_Kokuhaku_Jikkou_Iinkai_(Movie)": "Zutto_Mae_Kara_Suki_Deshita.:_Kokuhaku_Jikkou_Iinkai_(Movie)",

}
